package foxgrade.shim;

import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;

/** The per-colour block and item constants 26.2 folded into DYED_* colour collections. Generated. */
public final class BlocksCompat {
  private BlocksCompat() { }
  public static Block Blocks_WHITE_BANNER() { return (Block) Blocks.BANNER.white(); }
  public static Block Blocks_ORANGE_BANNER() { return (Block) Blocks.BANNER.orange(); }
  public static Block Blocks_MAGENTA_BANNER() { return (Block) Blocks.BANNER.magenta(); }
  public static Block Blocks_LIGHT_BLUE_BANNER() { return (Block) Blocks.BANNER.lightBlue(); }
  public static Block Blocks_YELLOW_BANNER() { return (Block) Blocks.BANNER.yellow(); }
  public static Block Blocks_LIME_BANNER() { return (Block) Blocks.BANNER.lime(); }
  public static Block Blocks_PINK_BANNER() { return (Block) Blocks.BANNER.pink(); }
  public static Block Blocks_GRAY_BANNER() { return (Block) Blocks.BANNER.gray(); }
  public static Block Blocks_LIGHT_GRAY_BANNER() { return (Block) Blocks.BANNER.lightGray(); }
  public static Block Blocks_CYAN_BANNER() { return (Block) Blocks.BANNER.cyan(); }
  public static Block Blocks_PURPLE_BANNER() { return (Block) Blocks.BANNER.purple(); }
  public static Block Blocks_BLUE_BANNER() { return (Block) Blocks.BANNER.blue(); }
  public static Block Blocks_BROWN_BANNER() { return (Block) Blocks.BANNER.brown(); }
  public static Block Blocks_GREEN_BANNER() { return (Block) Blocks.BANNER.green(); }
  public static Block Blocks_RED_BANNER() { return (Block) Blocks.BANNER.red(); }
  public static Block Blocks_BLACK_BANNER() { return (Block) Blocks.BANNER.black(); }
  public static Block Blocks_WHITE_BED() { return (Block) Blocks.BED.white(); }
  public static Block Blocks_ORANGE_BED() { return (Block) Blocks.BED.orange(); }
  public static Block Blocks_MAGENTA_BED() { return (Block) Blocks.BED.magenta(); }
  public static Block Blocks_LIGHT_BLUE_BED() { return (Block) Blocks.BED.lightBlue(); }
  public static Block Blocks_YELLOW_BED() { return (Block) Blocks.BED.yellow(); }
  public static Block Blocks_LIME_BED() { return (Block) Blocks.BED.lime(); }
  public static Block Blocks_PINK_BED() { return (Block) Blocks.BED.pink(); }
  public static Block Blocks_GRAY_BED() { return (Block) Blocks.BED.gray(); }
  public static Block Blocks_LIGHT_GRAY_BED() { return (Block) Blocks.BED.lightGray(); }
  public static Block Blocks_CYAN_BED() { return (Block) Blocks.BED.cyan(); }
  public static Block Blocks_PURPLE_BED() { return (Block) Blocks.BED.purple(); }
  public static Block Blocks_BLUE_BED() { return (Block) Blocks.BED.blue(); }
  public static Block Blocks_BROWN_BED() { return (Block) Blocks.BED.brown(); }
  public static Block Blocks_GREEN_BED() { return (Block) Blocks.BED.green(); }
  public static Block Blocks_RED_BED() { return (Block) Blocks.BED.red(); }
  public static Block Blocks_BLACK_BED() { return (Block) Blocks.BED.black(); }
  public static Block Blocks_WHITE_CARPET() { return (Block) Blocks.CARPET.white(); }
  public static Block Blocks_ORANGE_CARPET() { return (Block) Blocks.CARPET.orange(); }
  public static Block Blocks_MAGENTA_CARPET() { return (Block) Blocks.CARPET.magenta(); }
  public static Block Blocks_LIGHT_BLUE_CARPET() { return (Block) Blocks.CARPET.lightBlue(); }
  public static Block Blocks_YELLOW_CARPET() { return (Block) Blocks.CARPET.yellow(); }
  public static Block Blocks_LIME_CARPET() { return (Block) Blocks.CARPET.lime(); }
  public static Block Blocks_PINK_CARPET() { return (Block) Blocks.CARPET.pink(); }
  public static Block Blocks_GRAY_CARPET() { return (Block) Blocks.CARPET.gray(); }
  public static Block Blocks_LIGHT_GRAY_CARPET() { return (Block) Blocks.CARPET.lightGray(); }
  public static Block Blocks_CYAN_CARPET() { return (Block) Blocks.CARPET.cyan(); }
  public static Block Blocks_PURPLE_CARPET() { return (Block) Blocks.CARPET.purple(); }
  public static Block Blocks_BLUE_CARPET() { return (Block) Blocks.CARPET.blue(); }
  public static Block Blocks_BROWN_CARPET() { return (Block) Blocks.CARPET.brown(); }
  public static Block Blocks_GREEN_CARPET() { return (Block) Blocks.CARPET.green(); }
  public static Block Blocks_RED_CARPET() { return (Block) Blocks.CARPET.red(); }
  public static Block Blocks_BLACK_CARPET() { return (Block) Blocks.CARPET.black(); }
  public static Block Blocks_WHITE_CONCRETE() { return (Block) Blocks.CONCRETE.white(); }
  public static Block Blocks_ORANGE_CONCRETE() { return (Block) Blocks.CONCRETE.orange(); }
  public static Block Blocks_MAGENTA_CONCRETE() { return (Block) Blocks.CONCRETE.magenta(); }
  public static Block Blocks_LIGHT_BLUE_CONCRETE() { return (Block) Blocks.CONCRETE.lightBlue(); }
  public static Block Blocks_YELLOW_CONCRETE() { return (Block) Blocks.CONCRETE.yellow(); }
  public static Block Blocks_LIME_CONCRETE() { return (Block) Blocks.CONCRETE.lime(); }
  public static Block Blocks_PINK_CONCRETE() { return (Block) Blocks.CONCRETE.pink(); }
  public static Block Blocks_GRAY_CONCRETE() { return (Block) Blocks.CONCRETE.gray(); }
  public static Block Blocks_LIGHT_GRAY_CONCRETE() { return (Block) Blocks.CONCRETE.lightGray(); }
  public static Block Blocks_CYAN_CONCRETE() { return (Block) Blocks.CONCRETE.cyan(); }
  public static Block Blocks_PURPLE_CONCRETE() { return (Block) Blocks.CONCRETE.purple(); }
  public static Block Blocks_BLUE_CONCRETE() { return (Block) Blocks.CONCRETE.blue(); }
  public static Block Blocks_BROWN_CONCRETE() { return (Block) Blocks.CONCRETE.brown(); }
  public static Block Blocks_GREEN_CONCRETE() { return (Block) Blocks.CONCRETE.green(); }
  public static Block Blocks_RED_CONCRETE() { return (Block) Blocks.CONCRETE.red(); }
  public static Block Blocks_BLACK_CONCRETE() { return (Block) Blocks.CONCRETE.black(); }
  public static Block Blocks_WHITE_CONCRETE_POWDER() { return (Block) Blocks.CONCRETE_POWDER.white(); }
  public static Block Blocks_ORANGE_CONCRETE_POWDER() { return (Block) Blocks.CONCRETE_POWDER.orange(); }
  public static Block Blocks_MAGENTA_CONCRETE_POWDER() { return (Block) Blocks.CONCRETE_POWDER.magenta(); }
  public static Block Blocks_LIGHT_BLUE_CONCRETE_POWDER() { return (Block) Blocks.CONCRETE_POWDER.lightBlue(); }
  public static Block Blocks_YELLOW_CONCRETE_POWDER() { return (Block) Blocks.CONCRETE_POWDER.yellow(); }
  public static Block Blocks_LIME_CONCRETE_POWDER() { return (Block) Blocks.CONCRETE_POWDER.lime(); }
  public static Block Blocks_PINK_CONCRETE_POWDER() { return (Block) Blocks.CONCRETE_POWDER.pink(); }
  public static Block Blocks_GRAY_CONCRETE_POWDER() { return (Block) Blocks.CONCRETE_POWDER.gray(); }
  public static Block Blocks_LIGHT_GRAY_CONCRETE_POWDER() { return (Block) Blocks.CONCRETE_POWDER.lightGray(); }
  public static Block Blocks_CYAN_CONCRETE_POWDER() { return (Block) Blocks.CONCRETE_POWDER.cyan(); }
  public static Block Blocks_PURPLE_CONCRETE_POWDER() { return (Block) Blocks.CONCRETE_POWDER.purple(); }
  public static Block Blocks_BLUE_CONCRETE_POWDER() { return (Block) Blocks.CONCRETE_POWDER.blue(); }
  public static Block Blocks_BROWN_CONCRETE_POWDER() { return (Block) Blocks.CONCRETE_POWDER.brown(); }
  public static Block Blocks_GREEN_CONCRETE_POWDER() { return (Block) Blocks.CONCRETE_POWDER.green(); }
  public static Block Blocks_RED_CONCRETE_POWDER() { return (Block) Blocks.CONCRETE_POWDER.red(); }
  public static Block Blocks_BLACK_CONCRETE_POWDER() { return (Block) Blocks.CONCRETE_POWDER.black(); }
  public static Block Blocks_WHITE_CANDLE() { return (Block) Blocks.DYED_CANDLE.white(); }
  public static Block Blocks_ORANGE_CANDLE() { return (Block) Blocks.DYED_CANDLE.orange(); }
  public static Block Blocks_MAGENTA_CANDLE() { return (Block) Blocks.DYED_CANDLE.magenta(); }
  public static Block Blocks_LIGHT_BLUE_CANDLE() { return (Block) Blocks.DYED_CANDLE.lightBlue(); }
  public static Block Blocks_YELLOW_CANDLE() { return (Block) Blocks.DYED_CANDLE.yellow(); }
  public static Block Blocks_LIME_CANDLE() { return (Block) Blocks.DYED_CANDLE.lime(); }
  public static Block Blocks_PINK_CANDLE() { return (Block) Blocks.DYED_CANDLE.pink(); }
  public static Block Blocks_GRAY_CANDLE() { return (Block) Blocks.DYED_CANDLE.gray(); }
  public static Block Blocks_LIGHT_GRAY_CANDLE() { return (Block) Blocks.DYED_CANDLE.lightGray(); }
  public static Block Blocks_CYAN_CANDLE() { return (Block) Blocks.DYED_CANDLE.cyan(); }
  public static Block Blocks_PURPLE_CANDLE() { return (Block) Blocks.DYED_CANDLE.purple(); }
  public static Block Blocks_BLUE_CANDLE() { return (Block) Blocks.DYED_CANDLE.blue(); }
  public static Block Blocks_BROWN_CANDLE() { return (Block) Blocks.DYED_CANDLE.brown(); }
  public static Block Blocks_GREEN_CANDLE() { return (Block) Blocks.DYED_CANDLE.green(); }
  public static Block Blocks_RED_CANDLE() { return (Block) Blocks.DYED_CANDLE.red(); }
  public static Block Blocks_BLACK_CANDLE() { return (Block) Blocks.DYED_CANDLE.black(); }
  public static Block Blocks_WHITE_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.white(); }
  public static Block Blocks_ORANGE_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.orange(); }
  public static Block Blocks_MAGENTA_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.magenta(); }
  public static Block Blocks_LIGHT_BLUE_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.lightBlue(); }
  public static Block Blocks_YELLOW_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.yellow(); }
  public static Block Blocks_LIME_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.lime(); }
  public static Block Blocks_PINK_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.pink(); }
  public static Block Blocks_GRAY_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.gray(); }
  public static Block Blocks_LIGHT_GRAY_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.lightGray(); }
  public static Block Blocks_CYAN_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.cyan(); }
  public static Block Blocks_PURPLE_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.purple(); }
  public static Block Blocks_BLUE_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.blue(); }
  public static Block Blocks_BROWN_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.brown(); }
  public static Block Blocks_GREEN_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.green(); }
  public static Block Blocks_RED_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.red(); }
  public static Block Blocks_BLACK_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.black(); }
  public static Block Blocks_WHITE_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.white(); }
  public static Block Blocks_ORANGE_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.orange(); }
  public static Block Blocks_MAGENTA_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.magenta(); }
  public static Block Blocks_LIGHT_BLUE_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.lightBlue(); }
  public static Block Blocks_YELLOW_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.yellow(); }
  public static Block Blocks_LIME_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.lime(); }
  public static Block Blocks_PINK_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.pink(); }
  public static Block Blocks_GRAY_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.gray(); }
  public static Block Blocks_LIGHT_GRAY_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.lightGray(); }
  public static Block Blocks_CYAN_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.cyan(); }
  public static Block Blocks_PURPLE_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.purple(); }
  public static Block Blocks_BLUE_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.blue(); }
  public static Block Blocks_BROWN_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.brown(); }
  public static Block Blocks_GREEN_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.green(); }
  public static Block Blocks_RED_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.red(); }
  public static Block Blocks_BLACK_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.black(); }
  public static Block Blocks_WHITE_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.white(); }
  public static Block Blocks_ORANGE_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.orange(); }
  public static Block Blocks_MAGENTA_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.magenta(); }
  public static Block Blocks_LIGHT_BLUE_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.lightBlue(); }
  public static Block Blocks_YELLOW_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.yellow(); }
  public static Block Blocks_LIME_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.lime(); }
  public static Block Blocks_PINK_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.pink(); }
  public static Block Blocks_GRAY_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.gray(); }
  public static Block Blocks_LIGHT_GRAY_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.lightGray(); }
  public static Block Blocks_CYAN_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.cyan(); }
  public static Block Blocks_PURPLE_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.purple(); }
  public static Block Blocks_BLUE_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.blue(); }
  public static Block Blocks_BROWN_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.brown(); }
  public static Block Blocks_GREEN_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.green(); }
  public static Block Blocks_RED_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.red(); }
  public static Block Blocks_BLACK_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.black(); }
  public static Block Blocks_WHITE_GLAZED_TERRACOTTA() { return (Block) Blocks.GLAZED_TERRACOTTA.white(); }
  public static Block Blocks_ORANGE_GLAZED_TERRACOTTA() { return (Block) Blocks.GLAZED_TERRACOTTA.orange(); }
  public static Block Blocks_MAGENTA_GLAZED_TERRACOTTA() { return (Block) Blocks.GLAZED_TERRACOTTA.magenta(); }
  public static Block Blocks_LIGHT_BLUE_GLAZED_TERRACOTTA() { return (Block) Blocks.GLAZED_TERRACOTTA.lightBlue(); }
  public static Block Blocks_YELLOW_GLAZED_TERRACOTTA() { return (Block) Blocks.GLAZED_TERRACOTTA.yellow(); }
  public static Block Blocks_LIME_GLAZED_TERRACOTTA() { return (Block) Blocks.GLAZED_TERRACOTTA.lime(); }
  public static Block Blocks_PINK_GLAZED_TERRACOTTA() { return (Block) Blocks.GLAZED_TERRACOTTA.pink(); }
  public static Block Blocks_GRAY_GLAZED_TERRACOTTA() { return (Block) Blocks.GLAZED_TERRACOTTA.gray(); }
  public static Block Blocks_LIGHT_GRAY_GLAZED_TERRACOTTA() { return (Block) Blocks.GLAZED_TERRACOTTA.lightGray(); }
  public static Block Blocks_CYAN_GLAZED_TERRACOTTA() { return (Block) Blocks.GLAZED_TERRACOTTA.cyan(); }
  public static Block Blocks_PURPLE_GLAZED_TERRACOTTA() { return (Block) Blocks.GLAZED_TERRACOTTA.purple(); }
  public static Block Blocks_BLUE_GLAZED_TERRACOTTA() { return (Block) Blocks.GLAZED_TERRACOTTA.blue(); }
  public static Block Blocks_BROWN_GLAZED_TERRACOTTA() { return (Block) Blocks.GLAZED_TERRACOTTA.brown(); }
  public static Block Blocks_GREEN_GLAZED_TERRACOTTA() { return (Block) Blocks.GLAZED_TERRACOTTA.green(); }
  public static Block Blocks_RED_GLAZED_TERRACOTTA() { return (Block) Blocks.GLAZED_TERRACOTTA.red(); }
  public static Block Blocks_BLACK_GLAZED_TERRACOTTA() { return (Block) Blocks.GLAZED_TERRACOTTA.black(); }
  public static Block Blocks_WHITE_STAINED_GLASS() { return (Block) Blocks.STAINED_GLASS.white(); }
  public static Block Blocks_ORANGE_STAINED_GLASS() { return (Block) Blocks.STAINED_GLASS.orange(); }
  public static Block Blocks_MAGENTA_STAINED_GLASS() { return (Block) Blocks.STAINED_GLASS.magenta(); }
  public static Block Blocks_LIGHT_BLUE_STAINED_GLASS() { return (Block) Blocks.STAINED_GLASS.lightBlue(); }
  public static Block Blocks_YELLOW_STAINED_GLASS() { return (Block) Blocks.STAINED_GLASS.yellow(); }
  public static Block Blocks_LIME_STAINED_GLASS() { return (Block) Blocks.STAINED_GLASS.lime(); }
  public static Block Blocks_PINK_STAINED_GLASS() { return (Block) Blocks.STAINED_GLASS.pink(); }
  public static Block Blocks_GRAY_STAINED_GLASS() { return (Block) Blocks.STAINED_GLASS.gray(); }
  public static Block Blocks_LIGHT_GRAY_STAINED_GLASS() { return (Block) Blocks.STAINED_GLASS.lightGray(); }
  public static Block Blocks_CYAN_STAINED_GLASS() { return (Block) Blocks.STAINED_GLASS.cyan(); }
  public static Block Blocks_PURPLE_STAINED_GLASS() { return (Block) Blocks.STAINED_GLASS.purple(); }
  public static Block Blocks_BLUE_STAINED_GLASS() { return (Block) Blocks.STAINED_GLASS.blue(); }
  public static Block Blocks_BROWN_STAINED_GLASS() { return (Block) Blocks.STAINED_GLASS.brown(); }
  public static Block Blocks_GREEN_STAINED_GLASS() { return (Block) Blocks.STAINED_GLASS.green(); }
  public static Block Blocks_RED_STAINED_GLASS() { return (Block) Blocks.STAINED_GLASS.red(); }
  public static Block Blocks_BLACK_STAINED_GLASS() { return (Block) Blocks.STAINED_GLASS.black(); }
  public static Block Blocks_WHITE_STAINED_GLASS_PANE() { return (Block) Blocks.STAINED_GLASS_PANE.white(); }
  public static Block Blocks_ORANGE_STAINED_GLASS_PANE() { return (Block) Blocks.STAINED_GLASS_PANE.orange(); }
  public static Block Blocks_MAGENTA_STAINED_GLASS_PANE() { return (Block) Blocks.STAINED_GLASS_PANE.magenta(); }
  public static Block Blocks_LIGHT_BLUE_STAINED_GLASS_PANE() { return (Block) Blocks.STAINED_GLASS_PANE.lightBlue(); }
  public static Block Blocks_YELLOW_STAINED_GLASS_PANE() { return (Block) Blocks.STAINED_GLASS_PANE.yellow(); }
  public static Block Blocks_LIME_STAINED_GLASS_PANE() { return (Block) Blocks.STAINED_GLASS_PANE.lime(); }
  public static Block Blocks_PINK_STAINED_GLASS_PANE() { return (Block) Blocks.STAINED_GLASS_PANE.pink(); }
  public static Block Blocks_GRAY_STAINED_GLASS_PANE() { return (Block) Blocks.STAINED_GLASS_PANE.gray(); }
  public static Block Blocks_LIGHT_GRAY_STAINED_GLASS_PANE() { return (Block) Blocks.STAINED_GLASS_PANE.lightGray(); }
  public static Block Blocks_CYAN_STAINED_GLASS_PANE() { return (Block) Blocks.STAINED_GLASS_PANE.cyan(); }
  public static Block Blocks_PURPLE_STAINED_GLASS_PANE() { return (Block) Blocks.STAINED_GLASS_PANE.purple(); }
  public static Block Blocks_BLUE_STAINED_GLASS_PANE() { return (Block) Blocks.STAINED_GLASS_PANE.blue(); }
  public static Block Blocks_BROWN_STAINED_GLASS_PANE() { return (Block) Blocks.STAINED_GLASS_PANE.brown(); }
  public static Block Blocks_GREEN_STAINED_GLASS_PANE() { return (Block) Blocks.STAINED_GLASS_PANE.green(); }
  public static Block Blocks_RED_STAINED_GLASS_PANE() { return (Block) Blocks.STAINED_GLASS_PANE.red(); }
  public static Block Blocks_BLACK_STAINED_GLASS_PANE() { return (Block) Blocks.STAINED_GLASS_PANE.black(); }
  public static Block Blocks_WHITE_WALL_BANNER() { return (Block) Blocks.WALL_BANNER.white(); }
  public static Block Blocks_ORANGE_WALL_BANNER() { return (Block) Blocks.WALL_BANNER.orange(); }
  public static Block Blocks_MAGENTA_WALL_BANNER() { return (Block) Blocks.WALL_BANNER.magenta(); }
  public static Block Blocks_LIGHT_BLUE_WALL_BANNER() { return (Block) Blocks.WALL_BANNER.lightBlue(); }
  public static Block Blocks_YELLOW_WALL_BANNER() { return (Block) Blocks.WALL_BANNER.yellow(); }
  public static Block Blocks_LIME_WALL_BANNER() { return (Block) Blocks.WALL_BANNER.lime(); }
  public static Block Blocks_PINK_WALL_BANNER() { return (Block) Blocks.WALL_BANNER.pink(); }
  public static Block Blocks_GRAY_WALL_BANNER() { return (Block) Blocks.WALL_BANNER.gray(); }
  public static Block Blocks_LIGHT_GRAY_WALL_BANNER() { return (Block) Blocks.WALL_BANNER.lightGray(); }
  public static Block Blocks_CYAN_WALL_BANNER() { return (Block) Blocks.WALL_BANNER.cyan(); }
  public static Block Blocks_PURPLE_WALL_BANNER() { return (Block) Blocks.WALL_BANNER.purple(); }
  public static Block Blocks_BLUE_WALL_BANNER() { return (Block) Blocks.WALL_BANNER.blue(); }
  public static Block Blocks_BROWN_WALL_BANNER() { return (Block) Blocks.WALL_BANNER.brown(); }
  public static Block Blocks_GREEN_WALL_BANNER() { return (Block) Blocks.WALL_BANNER.green(); }
  public static Block Blocks_RED_WALL_BANNER() { return (Block) Blocks.WALL_BANNER.red(); }
  public static Block Blocks_BLACK_WALL_BANNER() { return (Block) Blocks.WALL_BANNER.black(); }
  public static Block Blocks_WHITE_WOOL() { return (Block) Blocks.WOOL.white(); }
  public static Block Blocks_ORANGE_WOOL() { return (Block) Blocks.WOOL.orange(); }
  public static Block Blocks_MAGENTA_WOOL() { return (Block) Blocks.WOOL.magenta(); }
  public static Block Blocks_LIGHT_BLUE_WOOL() { return (Block) Blocks.WOOL.lightBlue(); }
  public static Block Blocks_YELLOW_WOOL() { return (Block) Blocks.WOOL.yellow(); }
  public static Block Blocks_LIME_WOOL() { return (Block) Blocks.WOOL.lime(); }
  public static Block Blocks_PINK_WOOL() { return (Block) Blocks.WOOL.pink(); }
  public static Block Blocks_GRAY_WOOL() { return (Block) Blocks.WOOL.gray(); }
  public static Block Blocks_LIGHT_GRAY_WOOL() { return (Block) Blocks.WOOL.lightGray(); }
  public static Block Blocks_CYAN_WOOL() { return (Block) Blocks.WOOL.cyan(); }
  public static Block Blocks_PURPLE_WOOL() { return (Block) Blocks.WOOL.purple(); }
  public static Block Blocks_BLUE_WOOL() { return (Block) Blocks.WOOL.blue(); }
  public static Block Blocks_BROWN_WOOL() { return (Block) Blocks.WOOL.brown(); }
  public static Block Blocks_GREEN_WOOL() { return (Block) Blocks.WOOL.green(); }
  public static Block Blocks_RED_WOOL() { return (Block) Blocks.WOOL.red(); }
  public static Block Blocks_BLACK_WOOL() { return (Block) Blocks.WOOL.black(); }
  public static Item Items_WHITE_BANNER() { return (Item) Items.BANNER.white(); }
  public static Item Items_ORANGE_BANNER() { return (Item) Items.BANNER.orange(); }
  public static Item Items_MAGENTA_BANNER() { return (Item) Items.BANNER.magenta(); }
  public static Item Items_LIGHT_BLUE_BANNER() { return (Item) Items.BANNER.lightBlue(); }
  public static Item Items_YELLOW_BANNER() { return (Item) Items.BANNER.yellow(); }
  public static Item Items_LIME_BANNER() { return (Item) Items.BANNER.lime(); }
  public static Item Items_PINK_BANNER() { return (Item) Items.BANNER.pink(); }
  public static Item Items_GRAY_BANNER() { return (Item) Items.BANNER.gray(); }
  public static Item Items_LIGHT_GRAY_BANNER() { return (Item) Items.BANNER.lightGray(); }
  public static Item Items_CYAN_BANNER() { return (Item) Items.BANNER.cyan(); }
  public static Item Items_PURPLE_BANNER() { return (Item) Items.BANNER.purple(); }
  public static Item Items_BLUE_BANNER() { return (Item) Items.BANNER.blue(); }
  public static Item Items_BROWN_BANNER() { return (Item) Items.BANNER.brown(); }
  public static Item Items_GREEN_BANNER() { return (Item) Items.BANNER.green(); }
  public static Item Items_RED_BANNER() { return (Item) Items.BANNER.red(); }
  public static Item Items_BLACK_BANNER() { return (Item) Items.BANNER.black(); }
  public static Item Items_WHITE_BED() { return (Item) Items.BED.white(); }
  public static Item Items_ORANGE_BED() { return (Item) Items.BED.orange(); }
  public static Item Items_MAGENTA_BED() { return (Item) Items.BED.magenta(); }
  public static Item Items_LIGHT_BLUE_BED() { return (Item) Items.BED.lightBlue(); }
  public static Item Items_YELLOW_BED() { return (Item) Items.BED.yellow(); }
  public static Item Items_LIME_BED() { return (Item) Items.BED.lime(); }
  public static Item Items_PINK_BED() { return (Item) Items.BED.pink(); }
  public static Item Items_GRAY_BED() { return (Item) Items.BED.gray(); }
  public static Item Items_LIGHT_GRAY_BED() { return (Item) Items.BED.lightGray(); }
  public static Item Items_CYAN_BED() { return (Item) Items.BED.cyan(); }
  public static Item Items_PURPLE_BED() { return (Item) Items.BED.purple(); }
  public static Item Items_BLUE_BED() { return (Item) Items.BED.blue(); }
  public static Item Items_BROWN_BED() { return (Item) Items.BED.brown(); }
  public static Item Items_GREEN_BED() { return (Item) Items.BED.green(); }
  public static Item Items_RED_BED() { return (Item) Items.BED.red(); }
  public static Item Items_BLACK_BED() { return (Item) Items.BED.black(); }
  public static Item Items_WHITE_CARPET() { return (Item) Items.CARPET.white(); }
  public static Item Items_ORANGE_CARPET() { return (Item) Items.CARPET.orange(); }
  public static Item Items_MAGENTA_CARPET() { return (Item) Items.CARPET.magenta(); }
  public static Item Items_LIGHT_BLUE_CARPET() { return (Item) Items.CARPET.lightBlue(); }
  public static Item Items_YELLOW_CARPET() { return (Item) Items.CARPET.yellow(); }
  public static Item Items_LIME_CARPET() { return (Item) Items.CARPET.lime(); }
  public static Item Items_PINK_CARPET() { return (Item) Items.CARPET.pink(); }
  public static Item Items_GRAY_CARPET() { return (Item) Items.CARPET.gray(); }
  public static Item Items_LIGHT_GRAY_CARPET() { return (Item) Items.CARPET.lightGray(); }
  public static Item Items_CYAN_CARPET() { return (Item) Items.CARPET.cyan(); }
  public static Item Items_PURPLE_CARPET() { return (Item) Items.CARPET.purple(); }
  public static Item Items_BLUE_CARPET() { return (Item) Items.CARPET.blue(); }
  public static Item Items_BROWN_CARPET() { return (Item) Items.CARPET.brown(); }
  public static Item Items_GREEN_CARPET() { return (Item) Items.CARPET.green(); }
  public static Item Items_RED_CARPET() { return (Item) Items.CARPET.red(); }
  public static Item Items_BLACK_CARPET() { return (Item) Items.CARPET.black(); }
  public static Item Items_WHITE_CONCRETE() { return (Item) Items.CONCRETE.white(); }
  public static Item Items_ORANGE_CONCRETE() { return (Item) Items.CONCRETE.orange(); }
  public static Item Items_MAGENTA_CONCRETE() { return (Item) Items.CONCRETE.magenta(); }
  public static Item Items_LIGHT_BLUE_CONCRETE() { return (Item) Items.CONCRETE.lightBlue(); }
  public static Item Items_YELLOW_CONCRETE() { return (Item) Items.CONCRETE.yellow(); }
  public static Item Items_LIME_CONCRETE() { return (Item) Items.CONCRETE.lime(); }
  public static Item Items_PINK_CONCRETE() { return (Item) Items.CONCRETE.pink(); }
  public static Item Items_GRAY_CONCRETE() { return (Item) Items.CONCRETE.gray(); }
  public static Item Items_LIGHT_GRAY_CONCRETE() { return (Item) Items.CONCRETE.lightGray(); }
  public static Item Items_CYAN_CONCRETE() { return (Item) Items.CONCRETE.cyan(); }
  public static Item Items_PURPLE_CONCRETE() { return (Item) Items.CONCRETE.purple(); }
  public static Item Items_BLUE_CONCRETE() { return (Item) Items.CONCRETE.blue(); }
  public static Item Items_BROWN_CONCRETE() { return (Item) Items.CONCRETE.brown(); }
  public static Item Items_GREEN_CONCRETE() { return (Item) Items.CONCRETE.green(); }
  public static Item Items_RED_CONCRETE() { return (Item) Items.CONCRETE.red(); }
  public static Item Items_BLACK_CONCRETE() { return (Item) Items.CONCRETE.black(); }
  public static Item Items_WHITE_CONCRETE_POWDER() { return (Item) Items.CONCRETE_POWDER.white(); }
  public static Item Items_ORANGE_CONCRETE_POWDER() { return (Item) Items.CONCRETE_POWDER.orange(); }
  public static Item Items_MAGENTA_CONCRETE_POWDER() { return (Item) Items.CONCRETE_POWDER.magenta(); }
  public static Item Items_LIGHT_BLUE_CONCRETE_POWDER() { return (Item) Items.CONCRETE_POWDER.lightBlue(); }
  public static Item Items_YELLOW_CONCRETE_POWDER() { return (Item) Items.CONCRETE_POWDER.yellow(); }
  public static Item Items_LIME_CONCRETE_POWDER() { return (Item) Items.CONCRETE_POWDER.lime(); }
  public static Item Items_PINK_CONCRETE_POWDER() { return (Item) Items.CONCRETE_POWDER.pink(); }
  public static Item Items_GRAY_CONCRETE_POWDER() { return (Item) Items.CONCRETE_POWDER.gray(); }
  public static Item Items_LIGHT_GRAY_CONCRETE_POWDER() { return (Item) Items.CONCRETE_POWDER.lightGray(); }
  public static Item Items_CYAN_CONCRETE_POWDER() { return (Item) Items.CONCRETE_POWDER.cyan(); }
  public static Item Items_PURPLE_CONCRETE_POWDER() { return (Item) Items.CONCRETE_POWDER.purple(); }
  public static Item Items_BLUE_CONCRETE_POWDER() { return (Item) Items.CONCRETE_POWDER.blue(); }
  public static Item Items_BROWN_CONCRETE_POWDER() { return (Item) Items.CONCRETE_POWDER.brown(); }
  public static Item Items_GREEN_CONCRETE_POWDER() { return (Item) Items.CONCRETE_POWDER.green(); }
  public static Item Items_RED_CONCRETE_POWDER() { return (Item) Items.CONCRETE_POWDER.red(); }
  public static Item Items_BLACK_CONCRETE_POWDER() { return (Item) Items.CONCRETE_POWDER.black(); }
  public static Item Items_WHITE_DYE() { return (Item) Items.DYE.white(); }
  public static Item Items_ORANGE_DYE() { return (Item) Items.DYE.orange(); }
  public static Item Items_MAGENTA_DYE() { return (Item) Items.DYE.magenta(); }
  public static Item Items_LIGHT_BLUE_DYE() { return (Item) Items.DYE.lightBlue(); }
  public static Item Items_YELLOW_DYE() { return (Item) Items.DYE.yellow(); }
  public static Item Items_LIME_DYE() { return (Item) Items.DYE.lime(); }
  public static Item Items_PINK_DYE() { return (Item) Items.DYE.pink(); }
  public static Item Items_GRAY_DYE() { return (Item) Items.DYE.gray(); }
  public static Item Items_LIGHT_GRAY_DYE() { return (Item) Items.DYE.lightGray(); }
  public static Item Items_CYAN_DYE() { return (Item) Items.DYE.cyan(); }
  public static Item Items_PURPLE_DYE() { return (Item) Items.DYE.purple(); }
  public static Item Items_BLUE_DYE() { return (Item) Items.DYE.blue(); }
  public static Item Items_BROWN_DYE() { return (Item) Items.DYE.brown(); }
  public static Item Items_GREEN_DYE() { return (Item) Items.DYE.green(); }
  public static Item Items_RED_DYE() { return (Item) Items.DYE.red(); }
  public static Item Items_BLACK_DYE() { return (Item) Items.DYE.black(); }
  public static Item Items_WHITE_BUNDLE() { return (Item) Items.DYED_BUNDLE.white(); }
  public static Item Items_ORANGE_BUNDLE() { return (Item) Items.DYED_BUNDLE.orange(); }
  public static Item Items_MAGENTA_BUNDLE() { return (Item) Items.DYED_BUNDLE.magenta(); }
  public static Item Items_LIGHT_BLUE_BUNDLE() { return (Item) Items.DYED_BUNDLE.lightBlue(); }
  public static Item Items_YELLOW_BUNDLE() { return (Item) Items.DYED_BUNDLE.yellow(); }
  public static Item Items_LIME_BUNDLE() { return (Item) Items.DYED_BUNDLE.lime(); }
  public static Item Items_PINK_BUNDLE() { return (Item) Items.DYED_BUNDLE.pink(); }
  public static Item Items_GRAY_BUNDLE() { return (Item) Items.DYED_BUNDLE.gray(); }
  public static Item Items_LIGHT_GRAY_BUNDLE() { return (Item) Items.DYED_BUNDLE.lightGray(); }
  public static Item Items_CYAN_BUNDLE() { return (Item) Items.DYED_BUNDLE.cyan(); }
  public static Item Items_PURPLE_BUNDLE() { return (Item) Items.DYED_BUNDLE.purple(); }
  public static Item Items_BLUE_BUNDLE() { return (Item) Items.DYED_BUNDLE.blue(); }
  public static Item Items_BROWN_BUNDLE() { return (Item) Items.DYED_BUNDLE.brown(); }
  public static Item Items_GREEN_BUNDLE() { return (Item) Items.DYED_BUNDLE.green(); }
  public static Item Items_RED_BUNDLE() { return (Item) Items.DYED_BUNDLE.red(); }
  public static Item Items_BLACK_BUNDLE() { return (Item) Items.DYED_BUNDLE.black(); }
  public static Item Items_WHITE_CANDLE() { return (Item) Items.DYED_CANDLE.white(); }
  public static Item Items_ORANGE_CANDLE() { return (Item) Items.DYED_CANDLE.orange(); }
  public static Item Items_MAGENTA_CANDLE() { return (Item) Items.DYED_CANDLE.magenta(); }
  public static Item Items_LIGHT_BLUE_CANDLE() { return (Item) Items.DYED_CANDLE.lightBlue(); }
  public static Item Items_YELLOW_CANDLE() { return (Item) Items.DYED_CANDLE.yellow(); }
  public static Item Items_LIME_CANDLE() { return (Item) Items.DYED_CANDLE.lime(); }
  public static Item Items_PINK_CANDLE() { return (Item) Items.DYED_CANDLE.pink(); }
  public static Item Items_GRAY_CANDLE() { return (Item) Items.DYED_CANDLE.gray(); }
  public static Item Items_LIGHT_GRAY_CANDLE() { return (Item) Items.DYED_CANDLE.lightGray(); }
  public static Item Items_CYAN_CANDLE() { return (Item) Items.DYED_CANDLE.cyan(); }
  public static Item Items_PURPLE_CANDLE() { return (Item) Items.DYED_CANDLE.purple(); }
  public static Item Items_BLUE_CANDLE() { return (Item) Items.DYED_CANDLE.blue(); }
  public static Item Items_BROWN_CANDLE() { return (Item) Items.DYED_CANDLE.brown(); }
  public static Item Items_GREEN_CANDLE() { return (Item) Items.DYED_CANDLE.green(); }
  public static Item Items_RED_CANDLE() { return (Item) Items.DYED_CANDLE.red(); }
  public static Item Items_BLACK_CANDLE() { return (Item) Items.DYED_CANDLE.black(); }
  public static Item Items_WHITE_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.white(); }
  public static Item Items_ORANGE_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.orange(); }
  public static Item Items_MAGENTA_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.magenta(); }
  public static Item Items_LIGHT_BLUE_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.lightBlue(); }
  public static Item Items_YELLOW_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.yellow(); }
  public static Item Items_LIME_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.lime(); }
  public static Item Items_PINK_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.pink(); }
  public static Item Items_GRAY_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.gray(); }
  public static Item Items_LIGHT_GRAY_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.lightGray(); }
  public static Item Items_CYAN_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.cyan(); }
  public static Item Items_PURPLE_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.purple(); }
  public static Item Items_BLUE_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.blue(); }
  public static Item Items_BROWN_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.brown(); }
  public static Item Items_GREEN_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.green(); }
  public static Item Items_RED_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.red(); }
  public static Item Items_BLACK_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.black(); }
  public static Item Items_WHITE_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.white(); }
  public static Item Items_ORANGE_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.orange(); }
  public static Item Items_MAGENTA_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.magenta(); }
  public static Item Items_LIGHT_BLUE_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.lightBlue(); }
  public static Item Items_YELLOW_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.yellow(); }
  public static Item Items_LIME_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.lime(); }
  public static Item Items_PINK_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.pink(); }
  public static Item Items_GRAY_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.gray(); }
  public static Item Items_LIGHT_GRAY_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.lightGray(); }
  public static Item Items_CYAN_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.cyan(); }
  public static Item Items_PURPLE_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.purple(); }
  public static Item Items_BLUE_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.blue(); }
  public static Item Items_BROWN_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.brown(); }
  public static Item Items_GREEN_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.green(); }
  public static Item Items_RED_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.red(); }
  public static Item Items_BLACK_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.black(); }
  public static Item Items_WHITE_GLAZED_TERRACOTTA() { return (Item) Items.GLAZED_TERRACOTTA.white(); }
  public static Item Items_ORANGE_GLAZED_TERRACOTTA() { return (Item) Items.GLAZED_TERRACOTTA.orange(); }
  public static Item Items_MAGENTA_GLAZED_TERRACOTTA() { return (Item) Items.GLAZED_TERRACOTTA.magenta(); }
  public static Item Items_LIGHT_BLUE_GLAZED_TERRACOTTA() { return (Item) Items.GLAZED_TERRACOTTA.lightBlue(); }
  public static Item Items_YELLOW_GLAZED_TERRACOTTA() { return (Item) Items.GLAZED_TERRACOTTA.yellow(); }
  public static Item Items_LIME_GLAZED_TERRACOTTA() { return (Item) Items.GLAZED_TERRACOTTA.lime(); }
  public static Item Items_PINK_GLAZED_TERRACOTTA() { return (Item) Items.GLAZED_TERRACOTTA.pink(); }
  public static Item Items_GRAY_GLAZED_TERRACOTTA() { return (Item) Items.GLAZED_TERRACOTTA.gray(); }
  public static Item Items_LIGHT_GRAY_GLAZED_TERRACOTTA() { return (Item) Items.GLAZED_TERRACOTTA.lightGray(); }
  public static Item Items_CYAN_GLAZED_TERRACOTTA() { return (Item) Items.GLAZED_TERRACOTTA.cyan(); }
  public static Item Items_PURPLE_GLAZED_TERRACOTTA() { return (Item) Items.GLAZED_TERRACOTTA.purple(); }
  public static Item Items_BLUE_GLAZED_TERRACOTTA() { return (Item) Items.GLAZED_TERRACOTTA.blue(); }
  public static Item Items_BROWN_GLAZED_TERRACOTTA() { return (Item) Items.GLAZED_TERRACOTTA.brown(); }
  public static Item Items_GREEN_GLAZED_TERRACOTTA() { return (Item) Items.GLAZED_TERRACOTTA.green(); }
  public static Item Items_RED_GLAZED_TERRACOTTA() { return (Item) Items.GLAZED_TERRACOTTA.red(); }
  public static Item Items_BLACK_GLAZED_TERRACOTTA() { return (Item) Items.GLAZED_TERRACOTTA.black(); }
  public static Item Items_WHITE_HARNESS() { return (Item) Items.HARNESS.white(); }
  public static Item Items_ORANGE_HARNESS() { return (Item) Items.HARNESS.orange(); }
  public static Item Items_MAGENTA_HARNESS() { return (Item) Items.HARNESS.magenta(); }
  public static Item Items_LIGHT_BLUE_HARNESS() { return (Item) Items.HARNESS.lightBlue(); }
  public static Item Items_YELLOW_HARNESS() { return (Item) Items.HARNESS.yellow(); }
  public static Item Items_LIME_HARNESS() { return (Item) Items.HARNESS.lime(); }
  public static Item Items_PINK_HARNESS() { return (Item) Items.HARNESS.pink(); }
  public static Item Items_GRAY_HARNESS() { return (Item) Items.HARNESS.gray(); }
  public static Item Items_LIGHT_GRAY_HARNESS() { return (Item) Items.HARNESS.lightGray(); }
  public static Item Items_CYAN_HARNESS() { return (Item) Items.HARNESS.cyan(); }
  public static Item Items_PURPLE_HARNESS() { return (Item) Items.HARNESS.purple(); }
  public static Item Items_BLUE_HARNESS() { return (Item) Items.HARNESS.blue(); }
  public static Item Items_BROWN_HARNESS() { return (Item) Items.HARNESS.brown(); }
  public static Item Items_GREEN_HARNESS() { return (Item) Items.HARNESS.green(); }
  public static Item Items_RED_HARNESS() { return (Item) Items.HARNESS.red(); }
  public static Item Items_BLACK_HARNESS() { return (Item) Items.HARNESS.black(); }
  public static Item Items_WHITE_STAINED_GLASS() { return (Item) Items.STAINED_GLASS.white(); }
  public static Item Items_ORANGE_STAINED_GLASS() { return (Item) Items.STAINED_GLASS.orange(); }
  public static Item Items_MAGENTA_STAINED_GLASS() { return (Item) Items.STAINED_GLASS.magenta(); }
  public static Item Items_LIGHT_BLUE_STAINED_GLASS() { return (Item) Items.STAINED_GLASS.lightBlue(); }
  public static Item Items_YELLOW_STAINED_GLASS() { return (Item) Items.STAINED_GLASS.yellow(); }
  public static Item Items_LIME_STAINED_GLASS() { return (Item) Items.STAINED_GLASS.lime(); }
  public static Item Items_PINK_STAINED_GLASS() { return (Item) Items.STAINED_GLASS.pink(); }
  public static Item Items_GRAY_STAINED_GLASS() { return (Item) Items.STAINED_GLASS.gray(); }
  public static Item Items_LIGHT_GRAY_STAINED_GLASS() { return (Item) Items.STAINED_GLASS.lightGray(); }
  public static Item Items_CYAN_STAINED_GLASS() { return (Item) Items.STAINED_GLASS.cyan(); }
  public static Item Items_PURPLE_STAINED_GLASS() { return (Item) Items.STAINED_GLASS.purple(); }
  public static Item Items_BLUE_STAINED_GLASS() { return (Item) Items.STAINED_GLASS.blue(); }
  public static Item Items_BROWN_STAINED_GLASS() { return (Item) Items.STAINED_GLASS.brown(); }
  public static Item Items_GREEN_STAINED_GLASS() { return (Item) Items.STAINED_GLASS.green(); }
  public static Item Items_RED_STAINED_GLASS() { return (Item) Items.STAINED_GLASS.red(); }
  public static Item Items_BLACK_STAINED_GLASS() { return (Item) Items.STAINED_GLASS.black(); }
  public static Item Items_WHITE_STAINED_GLASS_PANE() { return (Item) Items.STAINED_GLASS_PANE.white(); }
  public static Item Items_ORANGE_STAINED_GLASS_PANE() { return (Item) Items.STAINED_GLASS_PANE.orange(); }
  public static Item Items_MAGENTA_STAINED_GLASS_PANE() { return (Item) Items.STAINED_GLASS_PANE.magenta(); }
  public static Item Items_LIGHT_BLUE_STAINED_GLASS_PANE() { return (Item) Items.STAINED_GLASS_PANE.lightBlue(); }
  public static Item Items_YELLOW_STAINED_GLASS_PANE() { return (Item) Items.STAINED_GLASS_PANE.yellow(); }
  public static Item Items_LIME_STAINED_GLASS_PANE() { return (Item) Items.STAINED_GLASS_PANE.lime(); }
  public static Item Items_PINK_STAINED_GLASS_PANE() { return (Item) Items.STAINED_GLASS_PANE.pink(); }
  public static Item Items_GRAY_STAINED_GLASS_PANE() { return (Item) Items.STAINED_GLASS_PANE.gray(); }
  public static Item Items_LIGHT_GRAY_STAINED_GLASS_PANE() { return (Item) Items.STAINED_GLASS_PANE.lightGray(); }
  public static Item Items_CYAN_STAINED_GLASS_PANE() { return (Item) Items.STAINED_GLASS_PANE.cyan(); }
  public static Item Items_PURPLE_STAINED_GLASS_PANE() { return (Item) Items.STAINED_GLASS_PANE.purple(); }
  public static Item Items_BLUE_STAINED_GLASS_PANE() { return (Item) Items.STAINED_GLASS_PANE.blue(); }
  public static Item Items_BROWN_STAINED_GLASS_PANE() { return (Item) Items.STAINED_GLASS_PANE.brown(); }
  public static Item Items_GREEN_STAINED_GLASS_PANE() { return (Item) Items.STAINED_GLASS_PANE.green(); }
  public static Item Items_RED_STAINED_GLASS_PANE() { return (Item) Items.STAINED_GLASS_PANE.red(); }
  public static Item Items_BLACK_STAINED_GLASS_PANE() { return (Item) Items.STAINED_GLASS_PANE.black(); }
  public static Item Items_WHITE_WOOL() { return (Item) Items.WOOL.white(); }
  public static Item Items_ORANGE_WOOL() { return (Item) Items.WOOL.orange(); }
  public static Item Items_MAGENTA_WOOL() { return (Item) Items.WOOL.magenta(); }
  public static Item Items_LIGHT_BLUE_WOOL() { return (Item) Items.WOOL.lightBlue(); }
  public static Item Items_YELLOW_WOOL() { return (Item) Items.WOOL.yellow(); }
  public static Item Items_LIME_WOOL() { return (Item) Items.WOOL.lime(); }
  public static Item Items_PINK_WOOL() { return (Item) Items.WOOL.pink(); }
  public static Item Items_GRAY_WOOL() { return (Item) Items.WOOL.gray(); }
  public static Item Items_LIGHT_GRAY_WOOL() { return (Item) Items.WOOL.lightGray(); }
  public static Item Items_CYAN_WOOL() { return (Item) Items.WOOL.cyan(); }
  public static Item Items_PURPLE_WOOL() { return (Item) Items.WOOL.purple(); }
  public static Item Items_BLUE_WOOL() { return (Item) Items.WOOL.blue(); }
  public static Item Items_BROWN_WOOL() { return (Item) Items.WOOL.brown(); }
  public static Item Items_GREEN_WOOL() { return (Item) Items.WOOL.green(); }
  public static Item Items_RED_WOOL() { return (Item) Items.WOOL.red(); }
  public static Item Items_BLACK_WOOL() { return (Item) Items.WOOL.black(); }
  public static Block Blocks_CHISELED_COPPER() { return (Block) Blocks.CHISELED_COPPER.weathering().unaffected(); }
  public static Block Blocks_EXPOSED_CHISELED_COPPER() { return (Block) Blocks.CHISELED_COPPER.weathering().exposed(); }
  public static Block Blocks_WEATHERED_CHISELED_COPPER() { return (Block) Blocks.CHISELED_COPPER.weathering().weathered(); }
  public static Block Blocks_OXIDIZED_CHISELED_COPPER() { return (Block) Blocks.CHISELED_COPPER.weathering().oxidized(); }
  public static Block Blocks_WAXED_CHISELED_COPPER() { return (Block) Blocks.CHISELED_COPPER.waxed().unaffected(); }
  public static Block Blocks_WAXED_EXPOSED_CHISELED_COPPER() { return (Block) Blocks.CHISELED_COPPER.waxed().exposed(); }
  public static Block Blocks_WAXED_WEATHERED_CHISELED_COPPER() { return (Block) Blocks.CHISELED_COPPER.waxed().weathered(); }
  public static Block Blocks_WAXED_OXIDIZED_CHISELED_COPPER() { return (Block) Blocks.CHISELED_COPPER.waxed().oxidized(); }
  public static Block Blocks_COPPER_BARS() { return (Block) Blocks.COPPER_BARS.weathering().unaffected(); }
  public static Block Blocks_EXPOSED_COPPER_BARS() { return (Block) Blocks.COPPER_BARS.weathering().exposed(); }
  public static Block Blocks_WEATHERED_COPPER_BARS() { return (Block) Blocks.COPPER_BARS.weathering().weathered(); }
  public static Block Blocks_OXIDIZED_COPPER_BARS() { return (Block) Blocks.COPPER_BARS.weathering().oxidized(); }
  public static Block Blocks_WAXED_COPPER_BARS() { return (Block) Blocks.COPPER_BARS.waxed().unaffected(); }
  public static Block Blocks_WAXED_EXPOSED_COPPER_BARS() { return (Block) Blocks.COPPER_BARS.waxed().exposed(); }
  public static Block Blocks_WAXED_WEATHERED_COPPER_BARS() { return (Block) Blocks.COPPER_BARS.waxed().weathered(); }
  public static Block Blocks_WAXED_OXIDIZED_COPPER_BARS() { return (Block) Blocks.COPPER_BARS.waxed().oxidized(); }
  public static Block Blocks_COPPER_BLOCK() { return (Block) Blocks.COPPER_BLOCK.weathering().unaffected(); }
  public static Block Blocks_EXPOSED_COPPER() { return (Block) Blocks.COPPER_BLOCK.weathering().exposed(); }
  public static Block Blocks_WEATHERED_COPPER() { return (Block) Blocks.COPPER_BLOCK.weathering().weathered(); }
  public static Block Blocks_OXIDIZED_COPPER() { return (Block) Blocks.COPPER_BLOCK.weathering().oxidized(); }
  public static Block Blocks_WAXED_COPPER_BLOCK() { return (Block) Blocks.COPPER_BLOCK.waxed().unaffected(); }
  public static Block Blocks_WAXED_EXPOSED_COPPER() { return (Block) Blocks.COPPER_BLOCK.waxed().exposed(); }
  public static Block Blocks_WAXED_WEATHERED_COPPER() { return (Block) Blocks.COPPER_BLOCK.waxed().weathered(); }
  public static Block Blocks_WAXED_OXIDIZED_COPPER() { return (Block) Blocks.COPPER_BLOCK.waxed().oxidized(); }
  public static Block Blocks_COPPER_BULB() { return (Block) Blocks.COPPER_BULB.weathering().unaffected(); }
  public static Block Blocks_EXPOSED_COPPER_BULB() { return (Block) Blocks.COPPER_BULB.weathering().exposed(); }
  public static Block Blocks_WEATHERED_COPPER_BULB() { return (Block) Blocks.COPPER_BULB.weathering().weathered(); }
  public static Block Blocks_OXIDIZED_COPPER_BULB() { return (Block) Blocks.COPPER_BULB.weathering().oxidized(); }
  public static Block Blocks_WAXED_COPPER_BULB() { return (Block) Blocks.COPPER_BULB.waxed().unaffected(); }
  public static Block Blocks_WAXED_EXPOSED_COPPER_BULB() { return (Block) Blocks.COPPER_BULB.waxed().exposed(); }
  public static Block Blocks_WAXED_WEATHERED_COPPER_BULB() { return (Block) Blocks.COPPER_BULB.waxed().weathered(); }
  public static Block Blocks_WAXED_OXIDIZED_COPPER_BULB() { return (Block) Blocks.COPPER_BULB.waxed().oxidized(); }
  public static Block Blocks_COPPER_CHAIN() { return (Block) Blocks.COPPER_CHAIN.weathering().unaffected(); }
  public static Block Blocks_EXPOSED_COPPER_CHAIN() { return (Block) Blocks.COPPER_CHAIN.weathering().exposed(); }
  public static Block Blocks_WEATHERED_COPPER_CHAIN() { return (Block) Blocks.COPPER_CHAIN.weathering().weathered(); }
  public static Block Blocks_OXIDIZED_COPPER_CHAIN() { return (Block) Blocks.COPPER_CHAIN.weathering().oxidized(); }
  public static Block Blocks_WAXED_COPPER_CHAIN() { return (Block) Blocks.COPPER_CHAIN.waxed().unaffected(); }
  public static Block Blocks_WAXED_EXPOSED_COPPER_CHAIN() { return (Block) Blocks.COPPER_CHAIN.waxed().exposed(); }
  public static Block Blocks_WAXED_WEATHERED_COPPER_CHAIN() { return (Block) Blocks.COPPER_CHAIN.waxed().weathered(); }
  public static Block Blocks_WAXED_OXIDIZED_COPPER_CHAIN() { return (Block) Blocks.COPPER_CHAIN.waxed().oxidized(); }
  public static Block Blocks_COPPER_CHEST() { return (Block) Blocks.COPPER_CHEST.weathering().unaffected(); }
  public static Block Blocks_EXPOSED_COPPER_CHEST() { return (Block) Blocks.COPPER_CHEST.weathering().exposed(); }
  public static Block Blocks_WEATHERED_COPPER_CHEST() { return (Block) Blocks.COPPER_CHEST.weathering().weathered(); }
  public static Block Blocks_OXIDIZED_COPPER_CHEST() { return (Block) Blocks.COPPER_CHEST.weathering().oxidized(); }
  public static Block Blocks_WAXED_COPPER_CHEST() { return (Block) Blocks.COPPER_CHEST.waxed().unaffected(); }
  public static Block Blocks_WAXED_EXPOSED_COPPER_CHEST() { return (Block) Blocks.COPPER_CHEST.waxed().exposed(); }
  public static Block Blocks_WAXED_WEATHERED_COPPER_CHEST() { return (Block) Blocks.COPPER_CHEST.waxed().weathered(); }
  public static Block Blocks_WAXED_OXIDIZED_COPPER_CHEST() { return (Block) Blocks.COPPER_CHEST.waxed().oxidized(); }
  public static Block Blocks_COPPER_DOOR() { return (Block) Blocks.COPPER_DOOR.weathering().unaffected(); }
  public static Block Blocks_EXPOSED_COPPER_DOOR() { return (Block) Blocks.COPPER_DOOR.weathering().exposed(); }
  public static Block Blocks_WEATHERED_COPPER_DOOR() { return (Block) Blocks.COPPER_DOOR.weathering().weathered(); }
  public static Block Blocks_OXIDIZED_COPPER_DOOR() { return (Block) Blocks.COPPER_DOOR.weathering().oxidized(); }
  public static Block Blocks_WAXED_COPPER_DOOR() { return (Block) Blocks.COPPER_DOOR.waxed().unaffected(); }
  public static Block Blocks_WAXED_EXPOSED_COPPER_DOOR() { return (Block) Blocks.COPPER_DOOR.waxed().exposed(); }
  public static Block Blocks_WAXED_WEATHERED_COPPER_DOOR() { return (Block) Blocks.COPPER_DOOR.waxed().weathered(); }
  public static Block Blocks_WAXED_OXIDIZED_COPPER_DOOR() { return (Block) Blocks.COPPER_DOOR.waxed().oxidized(); }
  public static Block Blocks_COPPER_GOLEM_STATUE() { return (Block) Blocks.COPPER_GOLEM_STATUE.weathering().unaffected(); }
  public static Block Blocks_EXPOSED_COPPER_GOLEM_STATUE() { return (Block) Blocks.COPPER_GOLEM_STATUE.weathering().exposed(); }
  public static Block Blocks_WEATHERED_COPPER_GOLEM_STATUE() { return (Block) Blocks.COPPER_GOLEM_STATUE.weathering().weathered(); }
  public static Block Blocks_OXIDIZED_COPPER_GOLEM_STATUE() { return (Block) Blocks.COPPER_GOLEM_STATUE.weathering().oxidized(); }
  public static Block Blocks_WAXED_COPPER_GOLEM_STATUE() { return (Block) Blocks.COPPER_GOLEM_STATUE.waxed().unaffected(); }
  public static Block Blocks_WAXED_EXPOSED_COPPER_GOLEM_STATUE() { return (Block) Blocks.COPPER_GOLEM_STATUE.waxed().exposed(); }
  public static Block Blocks_WAXED_WEATHERED_COPPER_GOLEM_STATUE() { return (Block) Blocks.COPPER_GOLEM_STATUE.waxed().weathered(); }
  public static Block Blocks_WAXED_OXIDIZED_COPPER_GOLEM_STATUE() { return (Block) Blocks.COPPER_GOLEM_STATUE.waxed().oxidized(); }
  public static Block Blocks_COPPER_GRATE() { return (Block) Blocks.COPPER_GRATE.weathering().unaffected(); }
  public static Block Blocks_EXPOSED_COPPER_GRATE() { return (Block) Blocks.COPPER_GRATE.weathering().exposed(); }
  public static Block Blocks_WEATHERED_COPPER_GRATE() { return (Block) Blocks.COPPER_GRATE.weathering().weathered(); }
  public static Block Blocks_OXIDIZED_COPPER_GRATE() { return (Block) Blocks.COPPER_GRATE.weathering().oxidized(); }
  public static Block Blocks_WAXED_COPPER_GRATE() { return (Block) Blocks.COPPER_GRATE.waxed().unaffected(); }
  public static Block Blocks_WAXED_EXPOSED_COPPER_GRATE() { return (Block) Blocks.COPPER_GRATE.waxed().exposed(); }
  public static Block Blocks_WAXED_WEATHERED_COPPER_GRATE() { return (Block) Blocks.COPPER_GRATE.waxed().weathered(); }
  public static Block Blocks_WAXED_OXIDIZED_COPPER_GRATE() { return (Block) Blocks.COPPER_GRATE.waxed().oxidized(); }
  public static Block Blocks_COPPER_LANTERN() { return (Block) Blocks.COPPER_LANTERN.weathering().unaffected(); }
  public static Block Blocks_EXPOSED_COPPER_LANTERN() { return (Block) Blocks.COPPER_LANTERN.weathering().exposed(); }
  public static Block Blocks_WEATHERED_COPPER_LANTERN() { return (Block) Blocks.COPPER_LANTERN.weathering().weathered(); }
  public static Block Blocks_OXIDIZED_COPPER_LANTERN() { return (Block) Blocks.COPPER_LANTERN.weathering().oxidized(); }
  public static Block Blocks_WAXED_COPPER_LANTERN() { return (Block) Blocks.COPPER_LANTERN.waxed().unaffected(); }
  public static Block Blocks_WAXED_EXPOSED_COPPER_LANTERN() { return (Block) Blocks.COPPER_LANTERN.waxed().exposed(); }
  public static Block Blocks_WAXED_WEATHERED_COPPER_LANTERN() { return (Block) Blocks.COPPER_LANTERN.waxed().weathered(); }
  public static Block Blocks_WAXED_OXIDIZED_COPPER_LANTERN() { return (Block) Blocks.COPPER_LANTERN.waxed().oxidized(); }
  public static Block Blocks_COPPER_TRAPDOOR() { return (Block) Blocks.COPPER_TRAPDOOR.weathering().unaffected(); }
  public static Block Blocks_EXPOSED_COPPER_TRAPDOOR() { return (Block) Blocks.COPPER_TRAPDOOR.weathering().exposed(); }
  public static Block Blocks_WEATHERED_COPPER_TRAPDOOR() { return (Block) Blocks.COPPER_TRAPDOOR.weathering().weathered(); }
  public static Block Blocks_OXIDIZED_COPPER_TRAPDOOR() { return (Block) Blocks.COPPER_TRAPDOOR.weathering().oxidized(); }
  public static Block Blocks_WAXED_COPPER_TRAPDOOR() { return (Block) Blocks.COPPER_TRAPDOOR.waxed().unaffected(); }
  public static Block Blocks_WAXED_EXPOSED_COPPER_TRAPDOOR() { return (Block) Blocks.COPPER_TRAPDOOR.waxed().exposed(); }
  public static Block Blocks_WAXED_WEATHERED_COPPER_TRAPDOOR() { return (Block) Blocks.COPPER_TRAPDOOR.waxed().weathered(); }
  public static Block Blocks_WAXED_OXIDIZED_COPPER_TRAPDOOR() { return (Block) Blocks.COPPER_TRAPDOOR.waxed().oxidized(); }
  public static Block Blocks_CUT_COPPER() { return (Block) Blocks.CUT_COPPER.weathering().unaffected(); }
  public static Block Blocks_EXPOSED_CUT_COPPER() { return (Block) Blocks.CUT_COPPER.weathering().exposed(); }
  public static Block Blocks_WEATHERED_CUT_COPPER() { return (Block) Blocks.CUT_COPPER.weathering().weathered(); }
  public static Block Blocks_OXIDIZED_CUT_COPPER() { return (Block) Blocks.CUT_COPPER.weathering().oxidized(); }
  public static Block Blocks_WAXED_CUT_COPPER() { return (Block) Blocks.CUT_COPPER.waxed().unaffected(); }
  public static Block Blocks_WAXED_EXPOSED_CUT_COPPER() { return (Block) Blocks.CUT_COPPER.waxed().exposed(); }
  public static Block Blocks_WAXED_WEATHERED_CUT_COPPER() { return (Block) Blocks.CUT_COPPER.waxed().weathered(); }
  public static Block Blocks_WAXED_OXIDIZED_CUT_COPPER() { return (Block) Blocks.CUT_COPPER.waxed().oxidized(); }
  public static Block Blocks_CUT_COPPER_SLAB() { return (Block) Blocks.CUT_COPPER_SLAB.weathering().unaffected(); }
  public static Block Blocks_EXPOSED_CUT_COPPER_SLAB() { return (Block) Blocks.CUT_COPPER_SLAB.weathering().exposed(); }
  public static Block Blocks_WEATHERED_CUT_COPPER_SLAB() { return (Block) Blocks.CUT_COPPER_SLAB.weathering().weathered(); }
  public static Block Blocks_OXIDIZED_CUT_COPPER_SLAB() { return (Block) Blocks.CUT_COPPER_SLAB.weathering().oxidized(); }
  public static Block Blocks_WAXED_CUT_COPPER_SLAB() { return (Block) Blocks.CUT_COPPER_SLAB.waxed().unaffected(); }
  public static Block Blocks_WAXED_EXPOSED_CUT_COPPER_SLAB() { return (Block) Blocks.CUT_COPPER_SLAB.waxed().exposed(); }
  public static Block Blocks_WAXED_WEATHERED_CUT_COPPER_SLAB() { return (Block) Blocks.CUT_COPPER_SLAB.waxed().weathered(); }
  public static Block Blocks_WAXED_OXIDIZED_CUT_COPPER_SLAB() { return (Block) Blocks.CUT_COPPER_SLAB.waxed().oxidized(); }
  public static Block Blocks_CUT_COPPER_STAIRS() { return (Block) Blocks.CUT_COPPER_STAIRS.weathering().unaffected(); }
  public static Block Blocks_EXPOSED_CUT_COPPER_STAIRS() { return (Block) Blocks.CUT_COPPER_STAIRS.weathering().exposed(); }
  public static Block Blocks_WEATHERED_CUT_COPPER_STAIRS() { return (Block) Blocks.CUT_COPPER_STAIRS.weathering().weathered(); }
  public static Block Blocks_OXIDIZED_CUT_COPPER_STAIRS() { return (Block) Blocks.CUT_COPPER_STAIRS.weathering().oxidized(); }
  public static Block Blocks_WAXED_CUT_COPPER_STAIRS() { return (Block) Blocks.CUT_COPPER_STAIRS.waxed().unaffected(); }
  public static Block Blocks_WAXED_EXPOSED_CUT_COPPER_STAIRS() { return (Block) Blocks.CUT_COPPER_STAIRS.waxed().exposed(); }
  public static Block Blocks_WAXED_WEATHERED_CUT_COPPER_STAIRS() { return (Block) Blocks.CUT_COPPER_STAIRS.waxed().weathered(); }
  public static Block Blocks_WAXED_OXIDIZED_CUT_COPPER_STAIRS() { return (Block) Blocks.CUT_COPPER_STAIRS.waxed().oxidized(); }
  public static Block Blocks_LIGHTNING_ROD() { return (Block) Blocks.LIGHTNING_ROD.weathering().unaffected(); }
  public static Block Blocks_EXPOSED_LIGHTNING_ROD() { return (Block) Blocks.LIGHTNING_ROD.weathering().exposed(); }
  public static Block Blocks_WEATHERED_LIGHTNING_ROD() { return (Block) Blocks.LIGHTNING_ROD.weathering().weathered(); }
  public static Block Blocks_OXIDIZED_LIGHTNING_ROD() { return (Block) Blocks.LIGHTNING_ROD.weathering().oxidized(); }
  public static Block Blocks_WAXED_LIGHTNING_ROD() { return (Block) Blocks.LIGHTNING_ROD.waxed().unaffected(); }
  public static Block Blocks_WAXED_EXPOSED_LIGHTNING_ROD() { return (Block) Blocks.LIGHTNING_ROD.waxed().exposed(); }
  public static Block Blocks_WAXED_WEATHERED_LIGHTNING_ROD() { return (Block) Blocks.LIGHTNING_ROD.waxed().weathered(); }
  public static Block Blocks_WAXED_OXIDIZED_LIGHTNING_ROD() { return (Block) Blocks.LIGHTNING_ROD.waxed().oxidized(); }
  public static Item Items_CHISELED_COPPER() { return (Item) Items.CHISELED_COPPER.weathering().unaffected(); }
  public static Item Items_EXPOSED_CHISELED_COPPER() { return (Item) Items.CHISELED_COPPER.weathering().exposed(); }
  public static Item Items_WEATHERED_CHISELED_COPPER() { return (Item) Items.CHISELED_COPPER.weathering().weathered(); }
  public static Item Items_OXIDIZED_CHISELED_COPPER() { return (Item) Items.CHISELED_COPPER.weathering().oxidized(); }
  public static Item Items_WAXED_CHISELED_COPPER() { return (Item) Items.CHISELED_COPPER.waxed().unaffected(); }
  public static Item Items_WAXED_EXPOSED_CHISELED_COPPER() { return (Item) Items.CHISELED_COPPER.waxed().exposed(); }
  public static Item Items_WAXED_WEATHERED_CHISELED_COPPER() { return (Item) Items.CHISELED_COPPER.waxed().weathered(); }
  public static Item Items_WAXED_OXIDIZED_CHISELED_COPPER() { return (Item) Items.CHISELED_COPPER.waxed().oxidized(); }
  public static Item Items_COPPER_BARS() { return (Item) Items.COPPER_BARS.weathering().unaffected(); }
  public static Item Items_EXPOSED_COPPER_BARS() { return (Item) Items.COPPER_BARS.weathering().exposed(); }
  public static Item Items_WEATHERED_COPPER_BARS() { return (Item) Items.COPPER_BARS.weathering().weathered(); }
  public static Item Items_OXIDIZED_COPPER_BARS() { return (Item) Items.COPPER_BARS.weathering().oxidized(); }
  public static Item Items_WAXED_COPPER_BARS() { return (Item) Items.COPPER_BARS.waxed().unaffected(); }
  public static Item Items_WAXED_EXPOSED_COPPER_BARS() { return (Item) Items.COPPER_BARS.waxed().exposed(); }
  public static Item Items_WAXED_WEATHERED_COPPER_BARS() { return (Item) Items.COPPER_BARS.waxed().weathered(); }
  public static Item Items_WAXED_OXIDIZED_COPPER_BARS() { return (Item) Items.COPPER_BARS.waxed().oxidized(); }
  public static Item Items_COPPER_BLOCK() { return (Item) Items.COPPER_BLOCK.weathering().unaffected(); }
  public static Item Items_EXPOSED_COPPER() { return (Item) Items.COPPER_BLOCK.weathering().exposed(); }
  public static Item Items_WEATHERED_COPPER() { return (Item) Items.COPPER_BLOCK.weathering().weathered(); }
  public static Item Items_OXIDIZED_COPPER() { return (Item) Items.COPPER_BLOCK.weathering().oxidized(); }
  public static Item Items_WAXED_COPPER_BLOCK() { return (Item) Items.COPPER_BLOCK.waxed().unaffected(); }
  public static Item Items_WAXED_EXPOSED_COPPER() { return (Item) Items.COPPER_BLOCK.waxed().exposed(); }
  public static Item Items_WAXED_WEATHERED_COPPER() { return (Item) Items.COPPER_BLOCK.waxed().weathered(); }
  public static Item Items_WAXED_OXIDIZED_COPPER() { return (Item) Items.COPPER_BLOCK.waxed().oxidized(); }
  public static Item Items_COPPER_BULB() { return (Item) Items.COPPER_BULB.weathering().unaffected(); }
  public static Item Items_EXPOSED_COPPER_BULB() { return (Item) Items.COPPER_BULB.weathering().exposed(); }
  public static Item Items_WEATHERED_COPPER_BULB() { return (Item) Items.COPPER_BULB.weathering().weathered(); }
  public static Item Items_OXIDIZED_COPPER_BULB() { return (Item) Items.COPPER_BULB.weathering().oxidized(); }
  public static Item Items_WAXED_COPPER_BULB() { return (Item) Items.COPPER_BULB.waxed().unaffected(); }
  public static Item Items_WAXED_EXPOSED_COPPER_BULB() { return (Item) Items.COPPER_BULB.waxed().exposed(); }
  public static Item Items_WAXED_WEATHERED_COPPER_BULB() { return (Item) Items.COPPER_BULB.waxed().weathered(); }
  public static Item Items_WAXED_OXIDIZED_COPPER_BULB() { return (Item) Items.COPPER_BULB.waxed().oxidized(); }
  public static Item Items_COPPER_CHAIN() { return (Item) Items.COPPER_CHAIN.weathering().unaffected(); }
  public static Item Items_EXPOSED_COPPER_CHAIN() { return (Item) Items.COPPER_CHAIN.weathering().exposed(); }
  public static Item Items_WEATHERED_COPPER_CHAIN() { return (Item) Items.COPPER_CHAIN.weathering().weathered(); }
  public static Item Items_OXIDIZED_COPPER_CHAIN() { return (Item) Items.COPPER_CHAIN.weathering().oxidized(); }
  public static Item Items_WAXED_COPPER_CHAIN() { return (Item) Items.COPPER_CHAIN.waxed().unaffected(); }
  public static Item Items_WAXED_EXPOSED_COPPER_CHAIN() { return (Item) Items.COPPER_CHAIN.waxed().exposed(); }
  public static Item Items_WAXED_WEATHERED_COPPER_CHAIN() { return (Item) Items.COPPER_CHAIN.waxed().weathered(); }
  public static Item Items_WAXED_OXIDIZED_COPPER_CHAIN() { return (Item) Items.COPPER_CHAIN.waxed().oxidized(); }
  public static Item Items_COPPER_CHEST() { return (Item) Items.COPPER_CHEST.weathering().unaffected(); }
  public static Item Items_EXPOSED_COPPER_CHEST() { return (Item) Items.COPPER_CHEST.weathering().exposed(); }
  public static Item Items_WEATHERED_COPPER_CHEST() { return (Item) Items.COPPER_CHEST.weathering().weathered(); }
  public static Item Items_OXIDIZED_COPPER_CHEST() { return (Item) Items.COPPER_CHEST.weathering().oxidized(); }
  public static Item Items_WAXED_COPPER_CHEST() { return (Item) Items.COPPER_CHEST.waxed().unaffected(); }
  public static Item Items_WAXED_EXPOSED_COPPER_CHEST() { return (Item) Items.COPPER_CHEST.waxed().exposed(); }
  public static Item Items_WAXED_WEATHERED_COPPER_CHEST() { return (Item) Items.COPPER_CHEST.waxed().weathered(); }
  public static Item Items_WAXED_OXIDIZED_COPPER_CHEST() { return (Item) Items.COPPER_CHEST.waxed().oxidized(); }
  public static Item Items_COPPER_DOOR() { return (Item) Items.COPPER_DOOR.weathering().unaffected(); }
  public static Item Items_EXPOSED_COPPER_DOOR() { return (Item) Items.COPPER_DOOR.weathering().exposed(); }
  public static Item Items_WEATHERED_COPPER_DOOR() { return (Item) Items.COPPER_DOOR.weathering().weathered(); }
  public static Item Items_OXIDIZED_COPPER_DOOR() { return (Item) Items.COPPER_DOOR.weathering().oxidized(); }
  public static Item Items_WAXED_COPPER_DOOR() { return (Item) Items.COPPER_DOOR.waxed().unaffected(); }
  public static Item Items_WAXED_EXPOSED_COPPER_DOOR() { return (Item) Items.COPPER_DOOR.waxed().exposed(); }
  public static Item Items_WAXED_WEATHERED_COPPER_DOOR() { return (Item) Items.COPPER_DOOR.waxed().weathered(); }
  public static Item Items_WAXED_OXIDIZED_COPPER_DOOR() { return (Item) Items.COPPER_DOOR.waxed().oxidized(); }
  public static Item Items_COPPER_GOLEM_STATUE() { return (Item) Items.COPPER_GOLEM_STATUE.weathering().unaffected(); }
  public static Item Items_EXPOSED_COPPER_GOLEM_STATUE() { return (Item) Items.COPPER_GOLEM_STATUE.weathering().exposed(); }
  public static Item Items_WEATHERED_COPPER_GOLEM_STATUE() { return (Item) Items.COPPER_GOLEM_STATUE.weathering().weathered(); }
  public static Item Items_OXIDIZED_COPPER_GOLEM_STATUE() { return (Item) Items.COPPER_GOLEM_STATUE.weathering().oxidized(); }
  public static Item Items_WAXED_COPPER_GOLEM_STATUE() { return (Item) Items.COPPER_GOLEM_STATUE.waxed().unaffected(); }
  public static Item Items_WAXED_EXPOSED_COPPER_GOLEM_STATUE() { return (Item) Items.COPPER_GOLEM_STATUE.waxed().exposed(); }
  public static Item Items_WAXED_WEATHERED_COPPER_GOLEM_STATUE() { return (Item) Items.COPPER_GOLEM_STATUE.waxed().weathered(); }
  public static Item Items_WAXED_OXIDIZED_COPPER_GOLEM_STATUE() { return (Item) Items.COPPER_GOLEM_STATUE.waxed().oxidized(); }
  public static Item Items_COPPER_GRATE() { return (Item) Items.COPPER_GRATE.weathering().unaffected(); }
  public static Item Items_EXPOSED_COPPER_GRATE() { return (Item) Items.COPPER_GRATE.weathering().exposed(); }
  public static Item Items_WEATHERED_COPPER_GRATE() { return (Item) Items.COPPER_GRATE.weathering().weathered(); }
  public static Item Items_OXIDIZED_COPPER_GRATE() { return (Item) Items.COPPER_GRATE.weathering().oxidized(); }
  public static Item Items_WAXED_COPPER_GRATE() { return (Item) Items.COPPER_GRATE.waxed().unaffected(); }
  public static Item Items_WAXED_EXPOSED_COPPER_GRATE() { return (Item) Items.COPPER_GRATE.waxed().exposed(); }
  public static Item Items_WAXED_WEATHERED_COPPER_GRATE() { return (Item) Items.COPPER_GRATE.waxed().weathered(); }
  public static Item Items_WAXED_OXIDIZED_COPPER_GRATE() { return (Item) Items.COPPER_GRATE.waxed().oxidized(); }
  public static Item Items_COPPER_LANTERN() { return (Item) Items.COPPER_LANTERN.weathering().unaffected(); }
  public static Item Items_EXPOSED_COPPER_LANTERN() { return (Item) Items.COPPER_LANTERN.weathering().exposed(); }
  public static Item Items_WEATHERED_COPPER_LANTERN() { return (Item) Items.COPPER_LANTERN.weathering().weathered(); }
  public static Item Items_OXIDIZED_COPPER_LANTERN() { return (Item) Items.COPPER_LANTERN.weathering().oxidized(); }
  public static Item Items_WAXED_COPPER_LANTERN() { return (Item) Items.COPPER_LANTERN.waxed().unaffected(); }
  public static Item Items_WAXED_EXPOSED_COPPER_LANTERN() { return (Item) Items.COPPER_LANTERN.waxed().exposed(); }
  public static Item Items_WAXED_WEATHERED_COPPER_LANTERN() { return (Item) Items.COPPER_LANTERN.waxed().weathered(); }
  public static Item Items_WAXED_OXIDIZED_COPPER_LANTERN() { return (Item) Items.COPPER_LANTERN.waxed().oxidized(); }
  public static Item Items_COPPER_TRAPDOOR() { return (Item) Items.COPPER_TRAPDOOR.weathering().unaffected(); }
  public static Item Items_EXPOSED_COPPER_TRAPDOOR() { return (Item) Items.COPPER_TRAPDOOR.weathering().exposed(); }
  public static Item Items_WEATHERED_COPPER_TRAPDOOR() { return (Item) Items.COPPER_TRAPDOOR.weathering().weathered(); }
  public static Item Items_OXIDIZED_COPPER_TRAPDOOR() { return (Item) Items.COPPER_TRAPDOOR.weathering().oxidized(); }
  public static Item Items_WAXED_COPPER_TRAPDOOR() { return (Item) Items.COPPER_TRAPDOOR.waxed().unaffected(); }
  public static Item Items_WAXED_EXPOSED_COPPER_TRAPDOOR() { return (Item) Items.COPPER_TRAPDOOR.waxed().exposed(); }
  public static Item Items_WAXED_WEATHERED_COPPER_TRAPDOOR() { return (Item) Items.COPPER_TRAPDOOR.waxed().weathered(); }
  public static Item Items_WAXED_OXIDIZED_COPPER_TRAPDOOR() { return (Item) Items.COPPER_TRAPDOOR.waxed().oxidized(); }
  public static Item Items_CUT_COPPER() { return (Item) Items.CUT_COPPER.weathering().unaffected(); }
  public static Item Items_EXPOSED_CUT_COPPER() { return (Item) Items.CUT_COPPER.weathering().exposed(); }
  public static Item Items_WEATHERED_CUT_COPPER() { return (Item) Items.CUT_COPPER.weathering().weathered(); }
  public static Item Items_OXIDIZED_CUT_COPPER() { return (Item) Items.CUT_COPPER.weathering().oxidized(); }
  public static Item Items_WAXED_CUT_COPPER() { return (Item) Items.CUT_COPPER.waxed().unaffected(); }
  public static Item Items_WAXED_EXPOSED_CUT_COPPER() { return (Item) Items.CUT_COPPER.waxed().exposed(); }
  public static Item Items_WAXED_WEATHERED_CUT_COPPER() { return (Item) Items.CUT_COPPER.waxed().weathered(); }
  public static Item Items_WAXED_OXIDIZED_CUT_COPPER() { return (Item) Items.CUT_COPPER.waxed().oxidized(); }
  public static Item Items_CUT_COPPER_SLAB() { return (Item) Items.CUT_COPPER_SLAB.weathering().unaffected(); }
  public static Item Items_EXPOSED_CUT_COPPER_SLAB() { return (Item) Items.CUT_COPPER_SLAB.weathering().exposed(); }
  public static Item Items_WEATHERED_CUT_COPPER_SLAB() { return (Item) Items.CUT_COPPER_SLAB.weathering().weathered(); }
  public static Item Items_OXIDIZED_CUT_COPPER_SLAB() { return (Item) Items.CUT_COPPER_SLAB.weathering().oxidized(); }
  public static Item Items_WAXED_CUT_COPPER_SLAB() { return (Item) Items.CUT_COPPER_SLAB.waxed().unaffected(); }
  public static Item Items_WAXED_EXPOSED_CUT_COPPER_SLAB() { return (Item) Items.CUT_COPPER_SLAB.waxed().exposed(); }
  public static Item Items_WAXED_WEATHERED_CUT_COPPER_SLAB() { return (Item) Items.CUT_COPPER_SLAB.waxed().weathered(); }
  public static Item Items_WAXED_OXIDIZED_CUT_COPPER_SLAB() { return (Item) Items.CUT_COPPER_SLAB.waxed().oxidized(); }
  public static Item Items_CUT_COPPER_STAIRS() { return (Item) Items.CUT_COPPER_STAIRS.weathering().unaffected(); }
  public static Item Items_EXPOSED_CUT_COPPER_STAIRS() { return (Item) Items.CUT_COPPER_STAIRS.weathering().exposed(); }
  public static Item Items_WEATHERED_CUT_COPPER_STAIRS() { return (Item) Items.CUT_COPPER_STAIRS.weathering().weathered(); }
  public static Item Items_OXIDIZED_CUT_COPPER_STAIRS() { return (Item) Items.CUT_COPPER_STAIRS.weathering().oxidized(); }
  public static Item Items_WAXED_CUT_COPPER_STAIRS() { return (Item) Items.CUT_COPPER_STAIRS.waxed().unaffected(); }
  public static Item Items_WAXED_EXPOSED_CUT_COPPER_STAIRS() { return (Item) Items.CUT_COPPER_STAIRS.waxed().exposed(); }
  public static Item Items_WAXED_WEATHERED_CUT_COPPER_STAIRS() { return (Item) Items.CUT_COPPER_STAIRS.waxed().weathered(); }
  public static Item Items_WAXED_OXIDIZED_CUT_COPPER_STAIRS() { return (Item) Items.CUT_COPPER_STAIRS.waxed().oxidized(); }
  public static Item Items_LIGHTNING_ROD() { return (Item) Items.LIGHTNING_ROD.weathering().unaffected(); }
  public static Item Items_EXPOSED_LIGHTNING_ROD() { return (Item) Items.LIGHTNING_ROD.weathering().exposed(); }
  public static Item Items_WEATHERED_LIGHTNING_ROD() { return (Item) Items.LIGHTNING_ROD.weathering().weathered(); }
  public static Item Items_OXIDIZED_LIGHTNING_ROD() { return (Item) Items.LIGHTNING_ROD.weathering().oxidized(); }
  public static Item Items_WAXED_LIGHTNING_ROD() { return (Item) Items.LIGHTNING_ROD.waxed().unaffected(); }
  public static Item Items_WAXED_EXPOSED_LIGHTNING_ROD() { return (Item) Items.LIGHTNING_ROD.waxed().exposed(); }
  public static Item Items_WAXED_WEATHERED_LIGHTNING_ROD() { return (Item) Items.LIGHTNING_ROD.waxed().weathered(); }
  public static Item Items_WAXED_OXIDIZED_LIGHTNING_ROD() { return (Item) Items.LIGHTNING_ROD.waxed().oxidized(); }
}
