package foxgrade.shim;

import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;

/** The per-colour block and item constants 26.2 folded into DYED_* colour collections. Generated. */
public final class BlocksCompat {
  private BlocksCompat() { }
  public static Block Blocks_WHITE_CANDLE() { return (Block) Blocks.DYED_CANDLE.white(); }
  public static Block Blocks_ORANGE_CANDLE() { return (Block) Blocks.DYED_CANDLE.orange(); }
  public static Block Blocks_MAGENTA_CANDLE() { return (Block) Blocks.DYED_CANDLE.magenta(); }
  public static Block Blocks_LIGHT_BLUE_CANDLE() { return (Block) Blocks.DYED_CANDLE.lightBlue(); }
  public static Block Blocks_YELLOW_CANDLE() { return (Block) Blocks.DYED_CANDLE.yellow(); }
  public static Block Blocks_LIME_CANDLE() { return (Block) Blocks.DYED_CANDLE.lime(); }
  public static Block Blocks_PINK_CANDLE() { return (Block) Blocks.DYED_CANDLE.pink(); }
  public static Block Blocks_GRAY_CANDLE() { return (Block) Blocks.DYED_CANDLE.gray(); }
  public static Block Blocks_LIGHT_GRAY_CANDLE() { return (Block) Blocks.DYED_CANDLE.lightGray(); }
  public static Block Blocks_CYAN_CANDLE() { return (Block) Blocks.DYED_CANDLE.cyan(); }
  public static Block Blocks_PURPLE_CANDLE() { return (Block) Blocks.DYED_CANDLE.purple(); }
  public static Block Blocks_BLUE_CANDLE() { return (Block) Blocks.DYED_CANDLE.blue(); }
  public static Block Blocks_BROWN_CANDLE() { return (Block) Blocks.DYED_CANDLE.brown(); }
  public static Block Blocks_GREEN_CANDLE() { return (Block) Blocks.DYED_CANDLE.green(); }
  public static Block Blocks_RED_CANDLE() { return (Block) Blocks.DYED_CANDLE.red(); }
  public static Block Blocks_BLACK_CANDLE() { return (Block) Blocks.DYED_CANDLE.black(); }
  public static Block Blocks_WHITE_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.white(); }
  public static Block Blocks_ORANGE_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.orange(); }
  public static Block Blocks_MAGENTA_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.magenta(); }
  public static Block Blocks_LIGHT_BLUE_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.lightBlue(); }
  public static Block Blocks_YELLOW_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.yellow(); }
  public static Block Blocks_LIME_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.lime(); }
  public static Block Blocks_PINK_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.pink(); }
  public static Block Blocks_GRAY_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.gray(); }
  public static Block Blocks_LIGHT_GRAY_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.lightGray(); }
  public static Block Blocks_CYAN_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.cyan(); }
  public static Block Blocks_PURPLE_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.purple(); }
  public static Block Blocks_BLUE_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.blue(); }
  public static Block Blocks_BROWN_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.brown(); }
  public static Block Blocks_GREEN_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.green(); }
  public static Block Blocks_RED_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.red(); }
  public static Block Blocks_BLACK_CANDLE_CAKE() { return (Block) Blocks.DYED_CANDLE_CAKE.black(); }
  public static Block Blocks_WHITE_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.white(); }
  public static Block Blocks_ORANGE_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.orange(); }
  public static Block Blocks_MAGENTA_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.magenta(); }
  public static Block Blocks_LIGHT_BLUE_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.lightBlue(); }
  public static Block Blocks_YELLOW_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.yellow(); }
  public static Block Blocks_LIME_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.lime(); }
  public static Block Blocks_PINK_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.pink(); }
  public static Block Blocks_GRAY_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.gray(); }
  public static Block Blocks_LIGHT_GRAY_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.lightGray(); }
  public static Block Blocks_CYAN_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.cyan(); }
  public static Block Blocks_PURPLE_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.purple(); }
  public static Block Blocks_BLUE_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.blue(); }
  public static Block Blocks_BROWN_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.brown(); }
  public static Block Blocks_GREEN_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.green(); }
  public static Block Blocks_RED_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.red(); }
  public static Block Blocks_BLACK_SHULKER_BOX() { return (Block) Blocks.DYED_SHULKER_BOX.black(); }
  public static Block Blocks_WHITE_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.white(); }
  public static Block Blocks_ORANGE_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.orange(); }
  public static Block Blocks_MAGENTA_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.magenta(); }
  public static Block Blocks_LIGHT_BLUE_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.lightBlue(); }
  public static Block Blocks_YELLOW_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.yellow(); }
  public static Block Blocks_LIME_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.lime(); }
  public static Block Blocks_PINK_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.pink(); }
  public static Block Blocks_GRAY_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.gray(); }
  public static Block Blocks_LIGHT_GRAY_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.lightGray(); }
  public static Block Blocks_CYAN_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.cyan(); }
  public static Block Blocks_PURPLE_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.purple(); }
  public static Block Blocks_BLUE_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.blue(); }
  public static Block Blocks_BROWN_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.brown(); }
  public static Block Blocks_GREEN_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.green(); }
  public static Block Blocks_RED_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.red(); }
  public static Block Blocks_BLACK_TERRACOTTA() { return (Block) Blocks.DYED_TERRACOTTA.black(); }
  public static Item Items_WHITE_BUNDLE() { return (Item) Items.DYED_BUNDLE.white(); }
  public static Item Items_ORANGE_BUNDLE() { return (Item) Items.DYED_BUNDLE.orange(); }
  public static Item Items_MAGENTA_BUNDLE() { return (Item) Items.DYED_BUNDLE.magenta(); }
  public static Item Items_LIGHT_BLUE_BUNDLE() { return (Item) Items.DYED_BUNDLE.lightBlue(); }
  public static Item Items_YELLOW_BUNDLE() { return (Item) Items.DYED_BUNDLE.yellow(); }
  public static Item Items_LIME_BUNDLE() { return (Item) Items.DYED_BUNDLE.lime(); }
  public static Item Items_PINK_BUNDLE() { return (Item) Items.DYED_BUNDLE.pink(); }
  public static Item Items_GRAY_BUNDLE() { return (Item) Items.DYED_BUNDLE.gray(); }
  public static Item Items_LIGHT_GRAY_BUNDLE() { return (Item) Items.DYED_BUNDLE.lightGray(); }
  public static Item Items_CYAN_BUNDLE() { return (Item) Items.DYED_BUNDLE.cyan(); }
  public static Item Items_PURPLE_BUNDLE() { return (Item) Items.DYED_BUNDLE.purple(); }
  public static Item Items_BLUE_BUNDLE() { return (Item) Items.DYED_BUNDLE.blue(); }
  public static Item Items_BROWN_BUNDLE() { return (Item) Items.DYED_BUNDLE.brown(); }
  public static Item Items_GREEN_BUNDLE() { return (Item) Items.DYED_BUNDLE.green(); }
  public static Item Items_RED_BUNDLE() { return (Item) Items.DYED_BUNDLE.red(); }
  public static Item Items_BLACK_BUNDLE() { return (Item) Items.DYED_BUNDLE.black(); }
  public static Item Items_WHITE_CANDLE() { return (Item) Items.DYED_CANDLE.white(); }
  public static Item Items_ORANGE_CANDLE() { return (Item) Items.DYED_CANDLE.orange(); }
  public static Item Items_MAGENTA_CANDLE() { return (Item) Items.DYED_CANDLE.magenta(); }
  public static Item Items_LIGHT_BLUE_CANDLE() { return (Item) Items.DYED_CANDLE.lightBlue(); }
  public static Item Items_YELLOW_CANDLE() { return (Item) Items.DYED_CANDLE.yellow(); }
  public static Item Items_LIME_CANDLE() { return (Item) Items.DYED_CANDLE.lime(); }
  public static Item Items_PINK_CANDLE() { return (Item) Items.DYED_CANDLE.pink(); }
  public static Item Items_GRAY_CANDLE() { return (Item) Items.DYED_CANDLE.gray(); }
  public static Item Items_LIGHT_GRAY_CANDLE() { return (Item) Items.DYED_CANDLE.lightGray(); }
  public static Item Items_CYAN_CANDLE() { return (Item) Items.DYED_CANDLE.cyan(); }
  public static Item Items_PURPLE_CANDLE() { return (Item) Items.DYED_CANDLE.purple(); }
  public static Item Items_BLUE_CANDLE() { return (Item) Items.DYED_CANDLE.blue(); }
  public static Item Items_BROWN_CANDLE() { return (Item) Items.DYED_CANDLE.brown(); }
  public static Item Items_GREEN_CANDLE() { return (Item) Items.DYED_CANDLE.green(); }
  public static Item Items_RED_CANDLE() { return (Item) Items.DYED_CANDLE.red(); }
  public static Item Items_BLACK_CANDLE() { return (Item) Items.DYED_CANDLE.black(); }
  public static Item Items_WHITE_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.white(); }
  public static Item Items_ORANGE_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.orange(); }
  public static Item Items_MAGENTA_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.magenta(); }
  public static Item Items_LIGHT_BLUE_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.lightBlue(); }
  public static Item Items_YELLOW_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.yellow(); }
  public static Item Items_LIME_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.lime(); }
  public static Item Items_PINK_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.pink(); }
  public static Item Items_GRAY_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.gray(); }
  public static Item Items_LIGHT_GRAY_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.lightGray(); }
  public static Item Items_CYAN_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.cyan(); }
  public static Item Items_PURPLE_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.purple(); }
  public static Item Items_BLUE_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.blue(); }
  public static Item Items_BROWN_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.brown(); }
  public static Item Items_GREEN_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.green(); }
  public static Item Items_RED_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.red(); }
  public static Item Items_BLACK_SHULKER_BOX() { return (Item) Items.DYED_SHULKER_BOX.black(); }
  public static Item Items_WHITE_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.white(); }
  public static Item Items_ORANGE_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.orange(); }
  public static Item Items_MAGENTA_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.magenta(); }
  public static Item Items_LIGHT_BLUE_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.lightBlue(); }
  public static Item Items_YELLOW_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.yellow(); }
  public static Item Items_LIME_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.lime(); }
  public static Item Items_PINK_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.pink(); }
  public static Item Items_GRAY_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.gray(); }
  public static Item Items_LIGHT_GRAY_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.lightGray(); }
  public static Item Items_CYAN_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.cyan(); }
  public static Item Items_PURPLE_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.purple(); }
  public static Item Items_BLUE_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.blue(); }
  public static Item Items_BROWN_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.brown(); }
  public static Item Items_GREEN_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.green(); }
  public static Item Items_RED_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.red(); }
  public static Item Items_BLACK_TERRACOTTA() { return (Item) Items.DYED_TERRACOTTA.black(); }
}
