package foxgrade.shim;

/** Built-in registries 1.21.x mods write into that 26.2 no longer has; generated by gen-render-bridges.py. */
public final class RegistriesCompat {
  private RegistriesCompat() {}
  private static net.minecraft.core.MappedRegistry<Object> ARMOR_MATERIAL;
  @SuppressWarnings({"unchecked", "rawtypes"})
  public static synchronized net.minecraft.core.Registry<?> reg_armor_material() { if (ARMOR_MATERIAL == null) ARMOR_MATERIAL = new net.minecraft.core.MappedRegistry(net.minecraft.resources.ResourceKey.createRegistryKey(net.minecraft.resources.Identifier.fromNamespaceAndPath("foxgrade", "armor_material")), com.mojang.serialization.Lifecycle.stable()); return ARMOR_MATERIAL; }
  public static net.minecraft.resources.ResourceKey<?> key_armor_material() { return reg_armor_material().key(); }

  private static net.minecraft.core.MappedRegistry<Object> CAT_VARIANT;
  @SuppressWarnings({"unchecked", "rawtypes"})
  public static synchronized net.minecraft.core.Registry<?> reg_cat_variant() { if (CAT_VARIANT == null) CAT_VARIANT = new net.minecraft.core.MappedRegistry(net.minecraft.resources.ResourceKey.createRegistryKey(net.minecraft.resources.Identifier.fromNamespaceAndPath("foxgrade", "cat_variant")), com.mojang.serialization.Lifecycle.stable()); return CAT_VARIANT; }
  private static net.minecraft.core.MappedRegistry<Object> FROG_VARIANT;
  @SuppressWarnings({"unchecked", "rawtypes"})
  public static synchronized net.minecraft.core.Registry<?> reg_frog_variant() { if (FROG_VARIANT == null) FROG_VARIANT = new net.minecraft.core.MappedRegistry(net.minecraft.resources.ResourceKey.createRegistryKey(net.minecraft.resources.Identifier.fromNamespaceAndPath("foxgrade", "frog_variant")), com.mojang.serialization.Lifecycle.stable()); return FROG_VARIANT; }
  private static net.minecraft.core.MappedRegistry<Object> INSTRUMENT;
  @SuppressWarnings({"unchecked", "rawtypes"})
  public static synchronized net.minecraft.core.Registry<?> reg_instrument() { if (INSTRUMENT == null) INSTRUMENT = new net.minecraft.core.MappedRegistry(net.minecraft.resources.ResourceKey.createRegistryKey(net.minecraft.resources.Identifier.fromNamespaceAndPath("foxgrade", "instrument")), com.mojang.serialization.Lifecycle.stable()); return INSTRUMENT; }
  private static net.minecraft.core.MappedRegistry<Object> ITEM_SUB_PREDICATE_TYPE;
  @SuppressWarnings({"unchecked", "rawtypes"})
  public static synchronized net.minecraft.core.Registry<?> reg_item_sub_predicate_type() { if (ITEM_SUB_PREDICATE_TYPE == null) ITEM_SUB_PREDICATE_TYPE = new net.minecraft.core.MappedRegistry(net.minecraft.resources.ResourceKey.createRegistryKey(net.minecraft.resources.Identifier.fromNamespaceAndPath("foxgrade", "item_sub_predicate_type")), com.mojang.serialization.Lifecycle.stable()); return ITEM_SUB_PREDICATE_TYPE; }
  public static net.minecraft.resources.ResourceKey<?> key_item_sub_predicate_type() { return reg_item_sub_predicate_type().key(); }

  private static net.minecraft.core.MappedRegistry<Object> SCHEDULE;
  @SuppressWarnings({"unchecked", "rawtypes"})
  public static synchronized net.minecraft.core.Registry<?> reg_schedule() { if (SCHEDULE == null) SCHEDULE = new net.minecraft.core.MappedRegistry(net.minecraft.resources.ResourceKey.createRegistryKey(net.minecraft.resources.Identifier.fromNamespaceAndPath("foxgrade", "schedule")), com.mojang.serialization.Lifecycle.stable()); return SCHEDULE; }
  public static net.minecraft.resources.ResourceKey<?> key_schedule() { return reg_schedule().key(); }

}
