#!/usr/bin/env python3
"""Build everything needed to measure one target version, so opening a version costs a run rather than an afternoon.

A version becomes supported when a corpus has been run against it. Every part of setting that up is mechanical and
was being done by hand: a launch classpath, a world the client will open, a Fabric API build, an options file that
stops the accessibility prompt swallowing quickPlay, and a runner. This does all of it.

Two details are easy to get wrong and are handled here. A world must be generated by that version's own server jar,
because a client will not open a world newer than itself. And the assetIndex comes from the version metadata rather
than being assumed — using the wrong one gives a client with no textures and a very confusing log.

Usage: make-instance.py <version> [<version>...]
"""
import json, pathlib, re, shutil, subprocess, sys, time, urllib.parse, urllib.request

HOME = pathlib.Path.home()
HERE = pathlib.Path(__file__).resolve().parent
MC = HOME / "Library/Application Support/minecraft"
UA = {"User-Agent": "foxgrade/1.1 (harness setup)"}


def meta_for(version):
    manifest = json.load(urllib.request.urlopen(urllib.request.Request(
        "https://piston-meta.mojang.com/mc/game/version_manifest_v2.json", headers=UA), timeout=30))
    entry = next((v for v in manifest["versions"] if v["id"] == version), None)
    if entry is None:
        raise SystemExit(f"Mojang publishes no version {version!r}")
    return json.load(urllib.request.urlopen(urllib.request.Request(entry["url"], headers=UA), timeout=60))


MAVEN = "https://maven.fabricmc.net/"
LOADER_CACHE = HOME / ".foxgrade-loaders"


def fabric_pieces(version):
    """Fabric Loader and its libraries, at a build contemporary with this Minecraft.

    Not the newest available. Loader 0.19 reads class tweakers, the format that replaced access wideners, and asked
    to load a Fabric API built for 1.21.2 it fails on the first module: "Failed to read classTweaker file from mod
    fabric-biome-api-v1". A loader from the era the mods are from reads what the mods actually contain."""
    meta = json.load(urllib.request.urlopen(urllib.request.Request(
        f"https://meta.fabricmc.net/v2/versions/loader/{version}", headers=UA), timeout=30))
    if not meta:
        raise SystemExit(f"Fabric publishes no loader for {version}")
    # Newest first, which is what a launcher would install and what the Fabric API build for a version expects:
    # 26.1's API declares fabricloader >=0.18.4 and refuses to load under an older one. An older loader is only
    # wanted for pre-26 games, whose API predates the class-tweaker format that loader 0.19 reads — and those are
    # blocked on the namespace question anyway, so preferring old by default was wrong for every version that can
    # actually be measured.
    builds = [m for m in meta]
    modern = int(version.split(".")[0]) >= 26
    # Pre-26 wants a loader old enough to still read the class-tweaker-free Fabric API of its era, but 0.16 was too
    # old to be a floor: Waystones declares fabricloader >= 0.17.3 and the whole run was graded a stall for a loader
    # the harness chose, not for anything the port did. Newest below 0.19 keeps the era constraint and clears the
    # floors real mods actually declare.
    def parts(m):
        return tuple(int(x) for x in m["loader"]["version"].split(".")[:3] if x.isdigit())
    era = sorted((m for m in builds if parts(m) < (0, 19)), key=parts, reverse=True)
    chosen = builds[0] if modern or not era else era[0]
    libs = [chosen["loader"]["maven"], chosen.get("intermediary", {}).get("maven")]
    for group in ("common", "client"):
        libs += [l["name"] for l in chosen["launcherMeta"].get("libraries", {}).get(group, [])]
    out = []
    LOADER_CACHE.mkdir(exist_ok=True)
    for coord in [c for c in libs if c]:
        g, a, v = coord.split(":")[:3]
        rel = f"{g.replace('.', '/')}/{a}/{v}/{a}-{v}.jar"
        dest = LOADER_CACHE / rel.replace("/", "_")
        if not dest.exists():
            for base in (MAVEN, "https://repo1.maven.org/maven2/"):
                try:
                    dest.write_bytes(urllib.request.urlopen(
                        urllib.request.Request(base + rel, headers=UA), timeout=180).read())
                    break
                except Exception:
                    continue
        if dest.exists():
            out.append(str(dest))
    return out


def classpath(meta, version):
    """That version's own libraries, plus the three things Fabric adds over vanilla."""
    out, seen = [], set()
    fabric = fabric_pieces(version)
    def artifact(path):
        """What library a jar is, regardless of where it sits. Two builds of ASM are still two copies of ASM, and
        Fabric Loader refuses to start when it finds both: "duplicate ASM classes found on classpath".

        Maven layout gives the artifact id in the path, but the loader cache is flat, so reading it from the path
        collapsed every cached jar to one key and silently kept only the first — which is how the intermediary
        mappings went missing and Fabric could not find the game at all."""
        name = pathlib.Path(path).name
        # The classifier is part of the identity. lwjgl-freetype-3.4.1.jar and
        # lwjgl-freetype-3.4.1-natives-macos.jar are not two builds of one library, they are the library and its
        # native payload — and treating them as duplicates dropped every natives jar, so the game died on
        # "Could not initialize class org.lwjgl.system.Library" before a single mod loaded.
        m = re.match(r"(.+?)-\d[\d.]*(?:-(.+?))?\.jar$", name.split("_")[-1] if "_" in name else name)
        if m:
            return m.group(1) + ("-" + m.group(2) if m.group(2) else "")
        parts = pathlib.Path(path).parts
        return parts[-3] if len(parts) >= 3 else pathlib.Path(path).stem

    for p in fabric:
        key = artifact(p)
        if key not in seen:
            seen.add(key); out.append(p)
    missing = []
    for lib in meta.get("libraries", []):
        rules = lib.get("rules")
        if rules:
            allow = False
            for r in rules:
                os_ = (r.get("os") or {}).get("name")
                if r.get("action") == "allow" and os_ in (None, "osx"): allow = True
                if r.get("action") == "disallow" and os_ == "osx": allow = False
            if not allow: continue
        art = (lib.get("downloads", {}) or {}).get("artifact")
        if art and art.get("path"):
            q = MC / "libraries" / art["path"]
            # Only versions the launcher has actually run have their libraries on disk. Skipping the rest silently
            # produced a classpath that looked complete and failed at runtime on whatever was missing —
            # NoClassDefFoundError: com/mojang/logging/LogUtils, from a jar nobody had downloaded.
            if not q.exists() and art.get("url"):
                for attempt in range(3):
                    try:
                        q.parent.mkdir(parents=True, exist_ok=True)
                        q.write_bytes(urllib.request.urlopen(
                            urllib.request.Request(art["url"], headers=UA), timeout=300).read())
                        break
                    except Exception as why:
                        if attempt == 2:
                            # Swallowing this is how 1.20.4 got a classpath with no LWJGL in it at all. The lane
                            # started, the game died on "Could not initialize class RenderSystem", and every mod in
                            # the corpus was recorded as a Fox-Grade failure -- 0 of 15, from a download that
                            # quietly did not happen. A classpath missing a library is not a classpath.
                            missing.append(f"{art['path']} ({why})")
            if q.exists() and artifact(q) not in seen:
                seen.add(artifact(q)); out.append(str(q))
    if missing:
        raise SystemExit(f"{version}: {len(missing)} librar(y/ies) could not be fetched, so this instance would "
                         f"measure its own classpath rather than Fox-Grade:\n  " + "\n  ".join(missing[:8]))
    jar = HERE / f"mc-{version}.jar"
    out.append(str(jar))
    return out


def fabric_api(version, into):
    q = urllib.parse.urlencode({"loaders": json.dumps(["fabric"]), "game_versions": json.dumps([version])})
    try:
        vs = json.load(urllib.request.urlopen(urllib.request.Request(
            f"https://api.modrinth.com/v2/project/fabric-api/version?{q}", headers=UA), timeout=30))
    except Exception:
        return None
    if not vs:
        return None
    f = vs[0]["files"][0]
    dest = into / f["filename"]
    if not dest.exists():
        dest.write_bytes(urllib.request.urlopen(urllib.request.Request(f["url"], headers=UA), timeout=300).read())
    return dest.name


def make_world(meta, version, saves, name):
    """Generated by this version's own server: a client refuses to open a world newer than itself."""
    if (saves / name).exists():
        return
    work = pathlib.Path(f"/tmp/genworld-{version}")
    work.mkdir(exist_ok=True)
    jar = work / "server.jar"
    if not jar.exists():
        jar.write_bytes(urllib.request.urlopen(urllib.request.Request(
            meta["downloads"]["server"]["url"], headers=UA), timeout=900).read())
    (work / "eula.txt").write_text("eula=true\n")
    (work / "server.properties").write_text(
        "level-name=world\nlevel-type=minecraft\\:flat\nonline-mode=false\nmax-world-size=1024\nview-distance=4\n")
    p = subprocess.Popen(["java", "-Xmx1G", "-jar", "server.jar", "nogui"], cwd=work,
                         stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    deadline = time.time() + 240
    while time.time() < deadline:
        line = p.stdout.readline()
        if not line or "Done (" in line:
            break
    p.terminate()
    try: p.wait(timeout=30)
    except Exception: p.kill()
    shutil.copytree(work / "world", saves / name)
    (saves / name / "session.lock").unlink(missing_ok=True)


def main():
    if len(sys.argv) < 2:
        print(__doc__); sys.exit(2)
    for version in sys.argv[1:]:
        print(f"\n=== {version} ===")
        meta = meta_for(version)
        asset = meta["assetIndex"]["id"]
        pt = HOME / f"mc-porttest-v{version.replace('.', '_')}"
        (pt / "mods").mkdir(parents=True, exist_ok=True)
        (pt / "fox-grade-inbox").mkdir(exist_ok=True)
        (pt / "saves").mkdir(exist_ok=True)
        (pt / "eula.txt").write_text("eula=true\n")
        opts = HOME / "mc-porttest/options.txt"
        if opts.exists():
            shutil.copy2(opts, pt / "options.txt")     # carries onboardAccessibility:false
        cp = classpath(meta, version)
        pathlib.Path(f"/tmp/fg-cp-{version}.txt").write_text(":".join(cp))
        # The asset index, written next to the classpath rather than only printed. A lane that has to rediscover it
        # by guessing at launcher paths finds nothing for a version the launcher never installed, and skips a
        # version whose instance is sitting right there, built and ready — which is how a night's breadth run
        # measured one version instead of ten.
        pathlib.Path(f"/tmp/fg-asset-{version}.txt").write_text(str(asset))
        api = fabric_api(version, pt / "mods")
        base = HOME / f"mc-porttest-v{version.replace('.', '_')}-base"
        base.mkdir(exist_ok=True)
        if api:
            shutil.copy2(pt / "mods" / api, base / api)
        make_world(meta, version, pt / "saves", "TESTWORLD")
        print(f"  instance {pt.name}: {len(cp)} classpath entries, assetIndex {asset}, "
              f"fabric-api {api or 'NONE PUBLISHED'}, world ready")


main()
